const searchByOrgans = [
  {
    "KRAS-12/13 Mutation Analysis Test": "kidney-3-300x300.jpg",
    "Allergy Panel 7 Drugs": "Blood-Cells-300x300.jpg",
    "Culture and Sensitivity, Synovial Fluid": "Bone-1-300x300.jpg",
    "Clostridium Difficile Toxin A and B, Stool": "Blood-Cells-300x300.jpg",
    "AFB Stain, CSF": "brain-spinalcord-300x300.jpg",
    "Acetone (Ketone), Serum": "liver-300x300.jpg",
    "Blood Culture and Sensitivity Final Report": "Blood-Culture-and-Sensitivity-Final-Report-300x300.jpg",
    "Calcium, Urine 24H": "kidney-3-300x300.jpg",
    "Bone Marrow Aspiration": "Bone-Marrow-Aspiration-300x300.jpg",
    "AFB Stain, ET Secretion": "lungs-300x300.jpg",
    "AFB Stain, Urine": "kidney-3-300x300.jpg",
    "AFB Stain, Synovial Fluid": "Joints-1-300x300.jpg",
    "Arsenic, Blood": "Blood-Cells-300x300.jpg",
    "Chlamydia Trachomatis IgM Antibody": "Blood-Cells-300x300.jpg",
    "Autoimmune Liver Profile": "autoimmune-liver-300x300.jpg",
    "Androstenedione (A4), Serum": "Gonads-300x300.png",
    "Catecholamines, Plasma": "Adrenal-Glands-300x300.jpg",
    "CA 15.3": "Blood-Cells-300x300.jpg",
    "Cocaine, Urine": "kidney-3-300x300.jpg",
    "Cobalt, Urine 24 H": "kidney-3-300x300.jpg",
    "Calcium, Ionized": "Blood-Cells-300x300.jpg",
    "Chromosomal Micro Array": "DNA-300x300.jpg",
    "Albumin/Globulin Ratio": "Albumin-Globulin-Ratio-300x300.jpg",
    "Aldosterone, Serum": "Adrenal-Glands-300x300.jpg",
    "CD 8 Count": "Blood-Cells-300x300.jpg",
    "AFB Stain, Guided Aspirate": "lungs-300x300.jpg",
    "Allergy Drug Panel MAXI": "50-300x300.jpg",
    "Chlorides, Urine Spot": "kidney-3-300x300.jpg",
    "Aspergillosis IGG": "Untitled-design-2-300x300.jpg",
    "Allergy Inhalant Panel": "Blood-Cells-300x300.jpg",
    "AFB Stain, Stool": "Stool-Sample-300x300.jpg",
    "Clopidogrel Sensitivity": "Blood-Cells-300x300.jpg",
    "Amino Acid Screen, Urine Quantitative": "kidney-3-300x300.jpg",
    "Antistreptolisin O (ASO)": "Blood-Cells-300x300.jpg",
    "Calcium, Dialysis Fluid": "kidney-3-300x300.jpg",
    "Bilirubin, Total": "liver-300x300.jpg",
    "Anti DNase B, Serum": "Blood-Cells-300x300.jpg",
    "Absolute Neutrophil Count (ANC)": "Bone-Marrow-300x300.jpg",
    "Beta-2-Glycoprotein I IgG Antibody Serum": "Blood-Cells-300x300.jpg",
    "AFB Stain, Tracheal secretion": "AFB-Stain-Tracheal-secretion-300x300.jpg",
    "BRCA 1 and 2 Profile": "BRCA-1-and-2-profile-300x300.jpg",
    "Allergy Food Panel": "Blood-Cells-300x300.jpg",
    "Antineutrophil Cytoplasmic Antibody (ANCA)": "Blood-Cells-300x300.jpg",
    "C-ANCA": "Blood-Cells-300x300.jpg",
    "Angiotensin Converting Enzyme (ACE)": "lungs-300x300.jpg",
    "Bence Jones Proteins, Urine": "kidney-3-300x300.jpg",
    "CA (Cyfra) 21-1, Serum": "lungs-300x300.jpg",
    "Acute Leukemia Comprehensive Panel": "Acute-Leukemia-Comprehensive-Panel-300x300.jpg",
    "Factor X (Stuart Factor) Activity, Plasma Test": "Sterility-Test-300x300.jpg",
    "Ferritin, Serum Test": "Blood-Cells-300x300.jpg",
    "Comprehensive Cardiology Panel": "heart-2-300x300.jpg",
    "Cell Count & Cell Type, Dialysis Fluid": "kidney-3-300x300.jpg",
    "Allergy for Gluten": "small-intestine-300x300.jpg",
    "Cardiolipin IgG Antibody": "Blood-Cells-300x300.jpg",
    "Acetylcholine Receptor Antibody": "lungs-300x300.jpg",
    "Estriol Unconjugated (E3)": "amniotic-300x300.jpg",
    "Electrolytes, Serum Test": "Blood-Cells-300x300.jpg",
    "Calprotectin, Stool Rapid": "22-300x300.jpg",
    "Electrolytes, Dialysis Fluid Test": "kidney-3-300x300.jpg",
    "Factor XI (Rosenthal) Activity, Plasma Test": "Sterility-Test-300x300.jpg",
    "Culture and Sensitivity, Fluid": "Culture-and-Sensitivity-Fluid-300x300.jpg",
    "Coagulation Profile Comprehensive Coagulation Profile": "coagulation-300x300.jpg",
    "AFB Stain, Sputum": "lungs-300x300.jpg",
    "C-Reactive Proteins (CRP)": "Blood-Cells-300x300.jpg",
    "Comprehensive Orthopedics Panel": "Bone-1-300x300.jpg",
    "BIOPSY GUN": "BIOPSY-GUN-300x300.jpg",
    "ASKA Skeletal (Striated) Muscle Antibody Serum": "32-300x300.jpg",
    "Congenital Alopecia T-Cell Immunodeficiency": "DNA-300x300.jpg",
    "AUTOMATED TB / AFB CULTURE SPUTUM": "AUTOMATED-TB-AFB-CULTURE-TISSUE-300x300.jpg",
    "Biochemical Analysis, Synovial Fluid": "Bone-1-300x300.jpg",
    "Factor V (Proaccelerin) Activity, Plasma Test": "Blood-Test-300x300.jpg",
    "Female Infertility Test": "amniotic-300x300.jpg",
    "AUTOMATED TB / AFB CULTURE CSF": "AUTOMATED-TB-AFB-CULTURE-PUS-300x300.jpg",
    "Creatinine, Urine Spot": "kidney-3-300x300.jpg",
    "Chlamydia Pneumoniae IgM Antibody": "Sterility-Test-300x300.jpg",
    "Fungal Culture, Hair Test": "Fungus-300x300.jpg",
    "CD 4 & CD 8 Count": "Blood-Cells-300x300.jpg",
    "Culture and Sensitivity, Catheter Tip": "Culture-and-Sensitivity-Catheter-Tip-300x300.jpg",
    "Comprehensive Gastroenterology Panel": "Stomach-300x300.jpg",
    "AFB Stain, Pericardial Fluid": "heart-2-300x300.jpg",
    "Cobalt, Blood": "Blood-Cells-300x300.jpg",
    "Fertility Profile Book the Most Reliable Fertility Profile": "fertility-300x300.jpg",
    "Bile Salts and Bile Pigments, Urine": "kidney-3-300x300.jpg",
    "Culture and Sensitivity, Bronchial Wash": "Culture-and-Sensitivity-Bronchial-Wash-300x300.jpg",
    "AOA-Anti Ovarian Antibody, Serum": "Blood-Cells-300x300.jpg",
    "AFB For Fluid": "AFB-For-Fluid-300x300.jpg",
    "Culture and Sensitivity, Drain Fluid": "Culture-and-Sensitivity-Drain-Fluid-300x300.jpg",
    "Culture and Sensitivity, Serous Fluid": "Culture-and-Sensitivity-Serous-Fluid-300x300.jpg",
    "Adreno Corticotrophic Hormone (ACTH)": "Blood-Cells-300x300.jpg",
    "Cholinesterase Acetyl, Plasma": "Blood-Cells-300x300.jpg",
    "Culture and Sensitivity, ET Tip Mixed Growth": "Culture-and-Sensitivity-ET-Tip-Mixed-Growth-300x300.jpg",
    "Amoebiasis IgG Antibody": "Intestines-300x300.jpg",
    "Cryptococcus Antigen, Serum": "Blood-Cells-300x300.jpg",
    "Folic Acid, RBC Test": "Blood-Cells-300x300.jpg",
    "Everolimus": "Everolimus-300x300.jpg",
    "Endomysial IgA Antibody, Serum Test": "Intestines-300x300.jpg",
    "Bicarbonate, Serum": "Blood-Cells-300x300.jpg",
    "Blood Culture and Sensitivity 2nd preliminary Report": "Blood-Culture-and-Sensitivity-2nd-preliminary-Report-300x300.jpg",
    "Factor-I (Fibrinogen) Activity Test": "Blood-Test-300x300.jpg",
    "Fungal Culture, Tissue Test": "Fungus-300x300.jpg",
    "CD 3, CD 4 & CD 8 Count": "Blood-Cells-300x300.jpg",
    "AFB Stain, Wound Swab": "AFB-Stain-Wound-Swab-300x300.jpg",
    "BRCA-1 & BRCA- 2": "Mammary-Gland-300x300.png",
    "Culture and Sensitivity, Pus": "Sterility-Test-300x300.jpg",
    "CA 19.9": "pancreas-1-300x300.jpg",
    "Cortisol, Free Urine 24H": "kidney-3-300x300.jpg",
    "ADAMTS 13 Autoantibody": "71-300x300.jpg",
    "Grams Stain, Stool Test": "Stool-Sample-300x300.jpg",
    "Culture and Sensitivity, Swab": "Culture-and-Sensitivity-Swab-300x300.jpg",
    "Bleeding Time Clotting Time (BT & CT)": "Bleeding-Time-Clotting-Time-BT-CT--300x300.jpg",
    "Grams Stain, Urine Test": "kidney-3-300x300.jpg",
    "Fungal Culture, Tracheal secretion": "Fungal-Culture-Tracheal-secretion-300x300.jpg",
    "AFB Stain, Pleural Fluid": "lungs-300x300.jpg"
  },
  {
    "Complete Urine Examination (CUE)": "urine-sample-300x300.jpg",
    "Absolute Reticulocyte Count": "Bone-Marrow-300x300.jpg",
    "Culture and Sensitivity, Pus Mixed Growth": "Culture-and-Sensitivity-Pus-Mixed-Growth-300x300.jpg",
    "Culture and Sensitivity, Nasal Swab": "Nose-Swab-300x300.jpg",
    "Aspergillosis IGM": "64-300x300.jpg",
    "Beta-2-Glycoprotein I IgA Antibody Serum": "Blood-Cells-300x300.jpg",
    "Chlorides, Urine 24 H": "kidney-3-300x300.jpg",
    "Glucose Challenge Test (GCT) Test": "Blood-Test-300x300.jpg",
    "Culture and Sensitivity with MIC values": "Culture-and-Sensitivity-with-MIC-values-300x300.jpg",
    "KOH Examination, Pus Test": "KOH-Examination-Pleural-fluid-300x300.jpg",
    "Factor V Leiden Mutant Detection, Blood Test": "Blood-Cells-300x300.jpg",
    "Cortisol (8 AM)": "Blood-Cells-300x300.jpg",
    "Cholinesterase Acetyl (RBC), Blood": "Blood-Cells-300x300.jpg",
    "JEV(Japanese Encephalitis) RNA Detection, CSF Test": "JAK2-V617-Mutation-with-Reflex-to-Jaks-Ex-12-CALR-EX-9-Mutation-and-MPL-W515-S505-MutationBoneM-300x300.jpg",
    "Jo-1 Antibody Test": "Brain-300x300.jpg",
    "Culture and Sensitivity, ET Tip": "Sterility-Test-300x300.jpg",
    "Absolute Monocyte Count": "Bone-Marrow-300x300.jpg",
    "KOH Examination, Pleural fluid": "KOH-Examination-Nasal-Secretion-300x300.jpg",
    "Biochemical Analysis, Peritoneal Fluid": "abdomen-300x300.jpg",
    "KOH Examination, CSF Fluid": "KOH-Examination-Corneal-Scrapings-300x300.jpg",
    "Culture and Sensitivity, CSF": "Culture-and-Sensitivity-CSF-300x300.jpg",
    "KOH Examination, TIP": "KOH-Examination-Throat-Swab-300x300.jpg",
    "Lipase, Urine Test": "pancreas-1-300x300.jpg",
    "Glucose, Urine Test": "urine-sample-300x300.jpg",
    "Cell Count & Cell Type, Synovial Fluid Test": "Bone-1-300x300.jpg",
    "Factor VIII Antigen (VW-Von Willebrand) Test": "Blood-Cells-300x300.jpg",
    "Chlamydia Trachomatis DNA, Urine": "urine-sample-300x300.jpg",
    "Epstein Bar Virus IgG Antibody (VCA)": "16-300x300.jpg",
    "Comprehensive Neurology Panel": "Brain-300x300.jpg",
    "Lactate Dehydrogenase (LDH), Serum Test": "Peritoneal-300x300.jpg",
    "Barbiturates, Urine Spot": "kidney-3-300x300.jpg",
    "Creatinine-GFR by MDRD": "kidney-3-300x300.jpg",
    "Acetaminophen (Paracetmol), Serum": "liver-300x300.jpg",
    "KOH Examination, Body Fluid": "lungs-300x300.jpg",
    "COVID-19 (RT PCR) AT OFFSITE": "68-300x300.jpg",
    "Leptin Test": "antibody-300x300.jpg",
    "CD19": "Blood-Cells-300x300.jpg",
    "Leishmania Antibody-IgG (Kala Azar) Test": "Nervous-System-300x300.jpg",
    "Amylase, Serum": "Digestive-System-300x300.jpg",
    "Grams Stain, Wound Swab Test": "wound-300x300.jpg",
    "Cannabis (Marijuana), Urine": "urine-sample-300x300.jpg",
    "Insulin Like Growth Factor (IGF)-1(Somatomedin C) Test": "antibody-300x300.jpg",
    "Chromosomal MicroArray High Resolution": "DNA-300x300.jpg",
    "Cadmium, Blood": "kidney-3-300x300.jpg",
    "AFB Stain, Gastric Aspirate Fluid": "AFB-Stain-Gastric-Aspirate-Fluid-300x300.jpg",
    "Alkaline Phosphatase with Bone Fraction (Ostase)": "liver-300x300.jpg",
    "Methadone (Dolophine), Urine Test": "Blood-Cells-300x300.jpg",
    "Morphine (Opiates), Urine Test": "antibody-300x300.jpg",
    "KOH Examination, Skin Scrappings Test": "Fungus-300x300.jpg",
    "LD (Leishmania Dodovani) Bodies, Blood Test": "antibody-300x300.jpg",
    "KOH Examination, Tissue Test": "KOH-Examination-TIP-300x300.jpg",
    "Amphiphysin (Neuronal Antigen) Antibody, Serum": "Brain-300x300.jpg",
    "Measles (Rubeola) IgG Antibody": "Measles-Rubeola-Serology-300x300.jpg",
    "Intact Parathyroid Hormone (iPTH) Test": "liver-300x300.jpg",
    "Myositis Profile-1 Test": "myositis-300x300.jpg",
    "Culture and Sensitivity, Cervical Swab": "Blood-Test-300x300.jpg",
    "Iron Profile Iron Profile Testing Near Me": "antibody-300x300.jpg",
    "Fatty Acids With Very Long Chains C22 To C26 Plasma": "Fatty-Acids-With-Very-Long-Chains-C22-To-C26-Plasma-300x300.jpg",
    "Free Beta HCG, Serum Test": "amniotic-300x300.jpg",
    "Cryptosporidium, Stool": "Sterility-Test-300x300.jpg",
    "CSF Analysis": "CSF-Analysis-300x300.jpg",
    "Leptospira Detection, Urine Test": "Brain-300x300.jpg",
    "Myoglobin Urine Spot Test": "21-300x300.jpg",
    "Factor VIII Activity (Anti Haemophilia A) Test": "Blood-Cells-300x300.jpg",
    "Cold Agglutination": "Blood-Cells-300x300.jpg",
    "Neuron Specific Enolase, Serum Test": "Neisseria-Gonorrhoea-DNA-Detection-By-Real-Time-PCR-Genital-Swab-300x300.jpg",
    "Absolute Lymphocyte Count": "Bone-Marrow-300x300.jpg",
    "Hanging Drop, Stool Test": "Stomach-Intestines-300x300.jpg",
    "Copper, Serum": "Blood-Cells-300x300.jpg",
    "Hepatitis E Virus (HEV) IgG Antibody Test": "liver-300x300.jpg",
    "Maternal Cell Contamination Test": "Stool-Sample-300x300.jpg",
    "Culture and Sensitivity, Sputum": "lungs-300x300.jpg",
    "Immunohistochemistry (2 Markers) Test": "Immunohistochemistry-1-Markers-300x300.jpg",
    "Myositis Profile-IgG(16 Antigen)": "antibody-300x300.jpg",
    "Creatinine Clearance Test, Urine 24H": "kidney-3-300x300.jpg",
    "GTT 2nd Hour Plasma Glucose": "GTT-2nd-Hour-Plasma-Glucose-300x300.jpg",
    "HIV-1-RNA Quantification (Viral Load) Test": "DNA-300x300.jpg",
    "Copper, Urine 24H": "kidney-3-300x300.jpg",
    "IHC-SINGLE MARKER (KI67)": "IHC-SINGLE-MARKER-HER2NU-300x300.jpg",
    "AFB Stain, Bronchial Wash": "lungs-300x300.jpg",
    "HSV DNA Detection I & II(CSF) Test": "DNA-300x300.jpg",
    "LC-1 (Liver Cytosolic Antigen type-1) Antibody Test": "Blood-Cells-300x300.jpg",
    "Iron Test": "iron-300x300.jpg",
    "Mycoplasma Pneumoniae IgG Antibody": "lungs-300x300.jpg",
    "Mitochondrial Antibody (AMA) Test": "MISMATCH-REPAIR-MMR-PROTEIN-IMMUNOHISTOCHEMISTRY-ONLY-300x300.jpg",
    "Homogentisic Acid Test": "urine-sample-300x300.jpg",
    "Fungal Culture, Nasal Secretion": "Fungal-Culture-Nasal-Secretion-300x300.jpg",
    "Hepatitis B Surface Antigen (HBSAG) Test": "antibody-300x300.jpg",
    "Lipoprotein-(a) Test": "lipid-300x300.jpg",
    "GAD 65 (Glutamic Acid Decarboxylase ) Antibodies Test": "Brain-300x300.jpg",
    "Culture and Sensitivity, Bal Fluid": "Culture-and-Sensitivity-Bal-Fluid-300x300.jpg",
    "Ammonia": "Intestines-300x300.jpg",
    "Fungal Culture, Skin Test": "Fungus-300x300.jpg",
    "Homocysteine Test": "Blood-Cells-300x300.jpg",
    "Histopathology Return of Blocks / Slides (Large)": "Histopathology-Return-of-Blocks-_-Slides-Large-300x300.jpg",
    "HLA B27 Test": "Immune-System-300x300.jpg",
    "Coombs Test Direct (DCT)": "Blood-Cells-300x300.jpg",
    "G6PD, Blood Test": "Blood-Cells-300x300.jpg",
    "COVID-19 (RT PCR) AT LAB": "68-300x300.jpg",
    "Electrolytes, Urine Spot Test": "kidney-3-300x300.jpg",
    "Anti Nuclear Antibody,(IFA Method)": "19-300x300.jpg",
    "Grams Stain, Pericardial Fluid Test": "heart-2-300x300.jpg",
    "Hepatitis C Virus Antibody (Anti HCV) Rapid Test": "antibody-300x300.jpg",
    "Culture and Sensitivity, Body Fluid": "Culture-and-Sensitivity-Body-Fluid-300x300.jpg",
    "Heinz Bodies, Blood Test": "Blood-Cells-300x300.jpg",
    "Magnesium Test": "kidney-3-300x300.jpg",
    "Calcitonin (Thyrocalcitonin), Serum": "Parathyroid-gland-300x300.jpg",
    "Methylmalonic Acidemia Test": "Methylmalonic-AcidQuantitative-Serum-300x300.jpg",
    "Alcohol (Ethanol), Quantitative, Urine": "kidney-3-300x300.jpg",
    "Albumin, Urine Spot": "kidney-3-300x300.jpg",
    "Cryptococcus Antigen, CSF": "Nervous-System-300x300.jpg",
    "Creatine Kinase (CPK)": "Blood-Cells-300x300.jpg",
    "HCV-total Antibody by CLIA Serum": "liver-300x300.jpg"
  },
  {
    "HCV-IgM Antibody": "0-300x300.jpg",
    "Lithium Test": "Blood-Cells-300x300.jpg",
    "Anti MAG (Myelin associated Glycoprotein) Ab": "Anti-MAG-Myelin-associated-Glycoprotein-Ab-300x300.jpg",
    "Hepatitis B Surface Antibody, Total (Anti HBS) Test": "antibody-300x300.jpg",
    "Cholesterol, HDL-Direct": "cholesterol-300x300.jpg",
    "Activated Partial Thromboplastin Time (APTT)": "liver-300x300.jpg",
    "Mumps IgG Antibody Test": "Blood-Test-300x300.jpg",
    "Carcinoembryonic Antigen (CEA)": "Blood-Cells-300x300.jpg",
    "Culture & Sensitivity , Tracheal secretion": "Culture-Sensitivity-Tracheal-secretion-300x300.jpg",
    "Bullous Pemphigoid 230": "Bullous-Pemphigoid-230-300x300.jpg",
    "Blood Culture and Sensitivity, Anaerobic-Profile": "Blood-Culture-and-Sensitivity-Anaerobic-1-300x300.jpg",
    "HLA-B27 Test": "Immune-System-300x300.jpg",
    "Culture And Sensitivity, Guided Aspirate": "Culture-and-Sensitivity-Guided-Aspirate-300x300.jpg",
    "Aldosterone/Renin Ratio": "kidney-3-300x300.jpg",
    "Histochemistry (special stain To Demonstarte Leprosy Bacilli)": "Histochemistry-special-stain-To-Demonstrate-Leprosy-Bacilli-300x300.jpg",
    "HLA B51, Blood Test": "Blood-Test-300x300.jpg",
    "Hepatitis C Virus (HCV) Antibody Elisa": "7-300x300.jpg",
    "Glomerular Basement Membrane (GBM) Antibody Test": "kidney-3-300x300.jpg",
    "Luteinizing Hormone (LH) Test": "blood-clotting-2-300x300.jpg",
    "Blood Culture and Sensitivity Anaerobic": "Blood-Culture-and-Sensitivity-Anaerobic-300x300.jpg",
    "KOH Examination, ET Secretion": "KOH-Examination-CSF-Fluid-300x300.jpg",
    "IBD Profile (Inflammatory Bowel Disease) IBD (Inflammatory Bowel Disease) Profile Near Me": "IHC-Immunohistochemistry-Lymphoma-Panel-300x300.jpg",
    "Aldosterone, Urine 24H": "kidney-3-300x300.jpg",
    "Entamoeba histolytica detection by Wet Mount Pus": "Entamoeba-histolytica-detection-by-Wet-Mount-Pus-300x300.jpg",
    "Beta 2 Microglobulin, Serum": "kidney-3-300x300.jpg",
    "HIV I & II Antibody Rapid Test": "antibody-300x300.jpg",
    "Haemogram Test": "Blood-Cells-300x300.jpg",
    "Leptospira IgM antibodies by EIA Serum": "antibody-300x300.jpg",
    "Breast Marker Profile": "breast-300x300.jpg",
    "Mercury, Urine 24H Test": "Sterility-Test-300x300.jpg",
    "Histopathology Return of Blocks / Slides (Small)": "Histopathology-Return-of-Blocks-_-Slides-Small-300x300.jpg",
    "Beta-D-Glucan Level by Protease Zymogen Colorimetry": "Beta-D-Glucan-Level-by-Protease-Zymogen-Colorimetry-300x300.jpg",
    "JAK2 V617 Mutation, with Reflex to Jaks Ex- 12, CALR EX-9 Mutation and MPL W515, S505 Mutation,BoneM": "Bone-1-300x300.jpg",
    "Culture and Sensitivity, Ear / Eye Swab": "Ears-300x300.jpg",
    "Alpha 1 Antitrypsin, Serum": "liver-300x300.jpg",
    "Culture and Sensitivity, Bartholin Fluid": "Culture-and-Sensitivity-Bartholin-Fluid-300x300.jpg",
    "Culture and Sensitivity, Stool": "Stool-Sample-300x300.jpg",
    "Allergy panel-Nuts": "23-300x300.jpg",
    "Lipid Profile Test": "pancreas-1-300x300.jpg",
    "HPV-DNA Detection (Qualitative) Test": "DNA-300x300.jpg",
    "Myasthenia Gravis Profile": "DNA-300x300.jpg",
    "C-ANCA-Elisa": "65-300x300.jpg",
    "Histopathology Slide Charges": "Histopathology-Slide-Charges-300x300.jpg",
    "KOH Examination, Stool": "lungs-300x300.jpg",
    "Apolipoprotein A1 & B": "Apolipoprotein-A1-B-300x300.jpg",
    "Lactate CSF Test": "DNA-300x300.jpg",
    "Heavy and Trace Metals profile-2": "Heavy-and-Trace-Metals-profile-2-300x300.jpg",
    "HIV Antibody Elisa": "62-300x300.jpg",
    "Factor VII (Proconvertin) Activity, Plasma Test": "liver-300x300.jpg",
    "MethylMalonic Acid(Quantitative), Serum": "urine-sample-300x300.jpg",
    "LKM I Antibody Test": "liver-300x300.jpg",
    "Antidiuretic Hormone ADH": "kidney-3-300x300.jpg",
    "Coxsackie IgG Antibody": "Digestive-Tract-300x300.jpg",
    "KOH Examination, Nasal Secretion": "Fungus-300x300.jpg",
    "HLA Cross Match Test": "kidney-3-300x300.jpg",
    "Leptospira Detection, Blood Test": "Blood-Cells-300x300.jpg",
    "Coxiella Burnetii IgG (Q Fever), Serum": "Blood-Cells-300x300.jpg",
    "Fibrinogen Degradation Product (FDP) Test": "Blood-Cells-300x300.jpg",
    "Biochemical Analysis, CSF": "brain-spinalcord-300x300.jpg",
    "Fecal Elastase": "Fecal-Elastase-300x300.jpg",
    "Calcium / Creatinine Ratio, Urine Spot": "kidney-3-300x300.jpg",
    "IGF BP3, Serum Test": "IDH1-300x300.jpg",
    "Chyle, Urine": "kidney-3-300x300.jpg",
    "CMV-DNA Viral Load (Quantitative), Plasma": "DNA-300x300.jpg",
    "Comprehensive Nephrology Panel": "kidney-3-300x300.jpg",
    "Microscope Urine": "Blood-Test-300x300.jpg",
    "Hemoglobin, Urine Test": "urine-sample-300x300.jpg",
    "Grams Stain, Pleural Fluid Test": "lungs-300x300.jpg",
    "Culture and Sensitivity, Peritoneal Fluid": "abdomen-300x300.jpg",
    "HLA-B 1502 for carbamazepine toxicity": "HLA-B-1502-for-carbamazepine-toxicity-300x300.jpg",
    "Hepatitis B Surface Antigen (HBSAG) Rapid test": "antibody-300x300.jpg",
    "IDH1 Test": "Bowel-Disease-300x300.jpg",
    "JAK-2 Mutation, Blood Test": "IRT-300x300.jpg",
    "HIV-2-RNA Quantification (Viral Load) Test": "DNA-300x300.jpg",
    "MCH Test": "amniotic-300x300.jpg",
    "Microfilaria Detection, Blood Test": "urine-sample-300x300.jpg",
    "Fungal Culture, Pleural Fluid": "Fungal-Culture-Pleural-Fluid-300x300.jpg",
    "Amino Levulinic Acid (ALA) Quantitative, Urine 24H": "urine-sample-300x300.jpg",
    "Globulin, Serum Test": "Globulin-Serum-300x300.jpg",
    "Amino Acid Screen-Qualitative, Plasma": "Blood-Cells-300x300.jpg",
    "High Sensitivity CRP (HS-CRP) Test": "liver-300x300.jpg",
    "Herpes Simplex Virus I IgM Test": "virus-300x300.jpg",
    "IRT": "Blood-Cells-300x300.jpg",
    "Natural Killer Cells (NKC), Blood Test": "Nose-Swab-300x300.jpg",
    "Entamoeba Histolytica (Amoebiasis) Antibody Test": "virus-1-300x300.jpg",
    "Automated TB/AFB Culture Interim Report -2": "Automated-TB-AFB-Culture-Interim-Report-2-300x300.jpg",
    "Hanta Virus IGM Antibodies, Serum Test": "Sterility-Test-300x300.jpg",
    "Measles (Rubeola) IgM Antibody": "antibody-300x300.jpg",
    "IHC-Breast Panel II (ER,PR,HER2NU,KI67)": "IHC-Breast-Panel-I-ERPRHER2NU-300x300.jpg",
    "CD20": "Blood-Cells-300x300.jpg",
    "ADA, Pleural Fluid": "lungs-300x300.jpg",
    "Hepatitis B Envelope Antigen (HBeAg) Elisa": "14-300x300.jpg",
    "Allergy Panel 12 Drugs": "Blood-Cells-300x300.jpg",
    "(IHC) Immunohistochemistry, Lymphoma Panel": "IHC-Immunohistochemistry-Final-Diagnostic-Panel-300x300.jpg",
    "Glucose, Post Lunch (PLBS) Test": "Blood-Cells-300x300.jpg",
    "Allergy Child Panel": "38-300x300.jpg",
    "Gastrointestinal panel by FilmArray (Biofire) Stool": "Gastrointestinal-panel-by-FilmArray-Biofire-Stool-300x300.jpg",
    "Hemophilia Profile Best Prices for Hemophilia Profile": "anaemia_clipdrop-enhance-300x300.jpg",
    "Factor V Leiden mutation": "Factor-V-Leiden-mutation-300x300.jpg",
    "Hepatitis E Virus (HEV) IgM Antibody Test": "liver-300x300.jpg",
    "Benzodiazepine, Spot Urine": "kidney-3-300x300.jpg",
    "C- Peptide": "pancreas-1-300x300.jpg",
    "HIV Antibody Test": "antibody-300x300.jpg",
    "Fungal Culture, Sputum Test": "lungs-300x300.jpg",
    "Hunters (MPS II) Test": "DNA-300x300.jpg",
    "HIV-1- DNA Detection (Qualitative) Test": "DNA-300x300.jpg",
    "Glycophorin A, Blood Test": "Blood-Test-300x300.jpg",
    "Immunohistochemistry Single Marker (Fish-Her2nu)": "Immunohistochemistry-8-Markers-300x300.jpg",
    "Cardiolipin IgA Antibody": "Blood-Cells-300x300.jpg",
    "Histopathology (Large) Test": "tissue-300x300.jpg",
    "Acute Leukemia Diagnostic Panel": "Bone-Marrow-300x300.jpg",
    "Culture and Sensitivity RO Water": "Culture-and-Sensitivity-RO-Water-300x300.jpg",
    "Cryoglobulin, Qualitative": "Blood-Cells-300x300.jpg"
  },
  {
    "Culture and Sensitivity, Pericardial Fluid": "heart-2-300x300.jpg",
    "Apolipoprotein B": "heart-2-300x300.jpg",
    "Inhibin B Test": "amniotic-300x300.jpg",
    "AUTOMATED TB / AFB CULTURE PUS": "AUTOMATED-TB-AFB-CULTURE-SPUTUM-300x300.jpg",
    "Complete Blood Picture (CBP)": "Blood-Cells-300x300.jpg",
    "Grams Stain, Synovial Fluid Test": "Joints-1-300x300.jpg",
    "Absolute Eosinophil Count (AEC)": "Bone-Marrow-300x300.jpg",
    "Calprotectin, Stool CLIA": "22-300x300.jpg",
    "Chemical Indicator Sterility Check": "Chemical-Indicator-Sterility-Check-300x300.jpg",
    "Grams Stain, Bronchial Wash Test": "lungs-300x300.jpg",
    "Arylsulphatase B, Blood": "Blood-Cells-300x300.jpg",
    "Leigh Syndrome Test": "kidney-3-300x300.jpg",
    "Immunocap Fruit Panel": "kidney-3-300x300.jpg",
    "HIV-1 RNA Detection, Qualitative Test": "DNA-300x300.jpg",
    "Hepatitis Delta Virus (HDV) Total Antibody Test": "antibody-300x300.jpg",
    "AST (SGOT)": "liver-300x300.jpg",
    "MPO/PR3 Antibodies, Serum Test": "MPN-Molecular-Reflex-Panel-300x300.jpg",
    "Gliadin IGA Antibody Test": "small-intestine-300x300.jpg",
    "Fungal Culture, Pus Test": "Fungus-300x300.jpg",
    "Microsporidium Detection by modified ZN Stain Stool": "Microscope-Urine-300x300.jpg",
    "Manganese, Blood Test": "Sperm-Test-300x300.jpg",
    "Anti Thrombin III Activity": "Blood-Cells-300x300.jpg",
    "Factor-II (Prothrombin) Mutation Detection, Blood Test": "Blood-Test-300x300.jpg",
    "Complete Blood Count (CBC)": "Blood-Cells-300x300.jpg",
    "Metanephrine, Urine 24H": "Sterility-Test-300x300.jpg",
    "Cardiac Risk Profile Get Tested with the Cardiac Risk": "heart-1-300x300.jpg",
    "Adrenaline (Epinephrine), Plasma": "Adrenal-Glands-300x300.jpg",
    "HEPATITIS C IGM": "7-300x300.jpg",
    "Helicobacter Pylori IgG antibodies by CLIA Serum": "35-300x300.jpg",
    "Grams Stain, Semen Test": "Sperm-Test-300x300.jpg",
    "Coxsackie IgM Antibody": "Digestive-Tract-300x300.jpg",
    "Culture and Sensitivity, Ascitic Fluid": "Culture-and-Sensitivity-Ascitic-Fluid-300x300.jpg",
    "Congenital Myotonia": "DNA-300x300.jpg",
    "Manganese, Serum Test": "Blood-Cells-300x300.jpg",
    "Culture and Sensitivity, Nail": "Culture-and-Sensitivity-Nail-300x300.jpg",
    "H.Pylori IGM Antibody Test": "Stomach-300x300.jpg",
    "Herpes (Varicella) Zoster IgM Antibody Test": "antibody-300x300.jpg",
    "Electrolytes, 24 H Urine Test": "kidney-3-300x300.jpg",
    "IHC-SINGLE MARKER (HER2NU)": "IHC-SINGLE-MARKER-ER-300x300.jpg",
    "Culture And Identification, Anaerobic Bacteria Blood Single Bottle": "29-300x300.jpg",
    "HFE Hemochromatosis Whole Gene Test": "DNA-300x300.jpg",
    "MISMATCH REPAIR (MMR) PROTEIN IMMUNOHISTOCHEMISTRY ONLY": "Stool-Sample-300x300.jpg",
    "Immunohistochemistry (3 Markers) Test": "antibody-300x300.jpg",
    "Blood Urea Nitrogen (BUN)": "kidney-3-300x300.jpg",
    "Angiotensin Converting Enzyme (ACE), CSF": "Angiotensin-Converting-Enzyme-ACE-CSF-300x300.jpg",
    "Grams Stain, Ascitic Fluid Test": "virus-1-300x300.jpg",
    "Factor XIII Activity Functional, Plasma Test": "Sterility-Test-300x300.jpg",
    "AFB Stain, Body Fluid": "AFB-Stain-Body-Fluid-300x300.jpg",
    "Immunohistochemistry (5 Markers) Test": "antibody-300x300.jpg",
    "Chlamydia Pneumoniae IgG Antibody": "virus-1-300x300.jpg",
    "Urine Cotinine Test": "Urea-Urine-Spot-300x300.jpg",
    "Phosphorous, Dialysis Fluid Test": "phospholipids-300x300.jpg",
    "Cell Count & Cell Type, Pericardial Fluid": "heart-2-300x300.jpg",
    "Glucose Challenge Test 1st Hour": "Glucose-Challenge-Test-1st-Hour-300x300.jpg",
    "IHC-Two markers (ER,PR)": "IHC-SINGLE-MARKER-PR-300x300.jpg",
    "BeautyMap": "DNA-300x300.jpg",
    "CPK MB": "Blood-Cells-300x300.jpg",
    "Culture and Sensitivity, Pleural Fluid": "lungs-300x300.jpg",
    "Cancer Detection Profile, Male Comprehensive Male Cancer Detection": "cancer-cells_clipdrop-enhance-300x300.jpg",
    "Chromosomal Microarray": "Brain-Nervous-System-300x300.jpg",
    "Monospot (Infectious Mononucleosis) Test": "antibody-300x300.jpg",
    "Culture and Sensitivity , ET Secretion": "Culture-and-Sensitivity-ET-Secretion-300x300.jpg",
    "Brucella IgG Antibody": "Blood-Cells-300x300.jpg",
    "Rheumatoid Factor IgM, Antibody": "Arthritis-300x300.jpg",
    "MTHFR Mutations": "DNA-300x300.jpg",
    "Platelet Count Test": "Adrenal-Glands-300x300.jpg",
    "Protein Total with Albumin Test": "kidney-3-300x300.jpg",
    "Leptospira IgG Antibody Test": "32-1-300x300.jpg",
    "Aldolase, Serum": "liver-300x300.jpg",
    "Beta HCG, Serum": "Sterility-Test-300x300.jpg",
    "Fat, Stool Test": "Stool-Sample-300x300.jpg",
    "C1 Esterase Inhibitor, Serum": "Blood-Cells-300x300.jpg",
    "Parainfluenza 1, 2 & 3, IgG Antibody, Serum Test": "Bone-1-300x300.jpg",
    "PAPP A Test": "P-ANCA-Elisa-300x300.jpg",
    "Folate, Serum (Vit B-9) Test": "Vitamin-300x300.jpg",
    "Logistics and Handling Charges": "liver-300x300.jpg",
    "Fragile X (FMR1)CGG Repeat Analysis": "Fragile-X-FMR1CGG-Repeat-Analysis-300x300.jpg",
    "Cell Count & cell Type, Peritoneal Fluid": "abdomen-300x300.jpg",
    "Lupus Anticoagulants (LAC) Test": "lungs-300x300.jpg",
    "Malaria QBC": "kidney-3-300x300.jpg",
    "AUTOMATED TB / AFB CULTURE Body fluids": "AUTOMATED-TB-AFB-CULTURE-CSF-300x300.jpg",
    "ADA, Peritoneal Fluid": "Peritoneal-300x300.jpg",
    "Cell Count & Cell Type, Ascitic Fluid": "abdomen-300x300.jpg",
    "PCOD Profile Assess PCOD with Comprehensive PCOD Profile": "26-300x300.jpg",
    "Comprehensive Pulmonology Panel": "lungs-300x300.jpg",
    "Rubella IgM Antibody ": "Stool-Sample-300x300.jpg",
    "P1NP (Total N-Terminal Propeptide Of Type I Procol) Test": "BCR-ABL-IS-International-Scale-Transcript-fusion-Quantification-by-Real-Time-PCR-Minor-1-300x300.jpg",
    "Fungal AST": "Fungal-AST-300x300.jpg",
    "PML Ra Ra t(15:17) Qualitative By PCR": "Plasminogen-Activator-Inhibitor-1-PAI-1-300x300.jpg",
    "Levetiracetam, Serum Test": "Leukemia-Panel-by-FISH-CLL-300x300.jpg",
    "Herpes Simplex Virus II IgG Test": "antibody-300x300.jpg",
    "Ornithine Quantitative Plasma": "Oral-Glucose-Tolerance-Test-O-GTT-Plasma-300x300.jpg",
    "Free Androgen Index (FAI), Serum Test": "Blood-Test-300x300.jpg",
    "Peripheral Smear for Abnormal Cells Test": "26-300x300.jpg",
    "Hepatitis A Virus Antibody, (IGG) Total Test": "antibody-300x300.jpg",
    "Creatinine, Serum": "kidney-3-300x300.jpg",
    "Allergy-Grass Panel": "40-300x300.jpg",
    "Leptospira Detection, CSF Test": "Blood-Cells-300x300.jpg",
    "Mercury, Blood Test": "Meningitis-panel-CSF-multiplex-PCR-300x300.jpg",
    "Immature Platelet Fraction Test": "IHC-Two-markers-ERPR-300x300.jpg",
    "Comprehensive Pediatrics Panel": "Sterility-Test-300x300.jpg",
    "HLA B 5, Blood Test": "Blood-Test-300x300.jpg",
    "Immunohistochemistry (4 Markers) Test": "antibody-300x300.jpg",
    "Prostate Specific Antigen, Free Test": "Blood-Test-300x300.jpg",
    "Carbamazepine (Tegretol)": "Blood-Cells-300x300.jpg",
    "GTT 1 1/2 Hour Plasma Glucose": "GTT-1-1-2-Hour-Plasma-Glucose-300x300.jpg",
    "Coxiella Burnetii IgM (Q Fever), Serum": "Blood-Cells-300x300.jpg",
    "Culture and Sensitivity, Nipple discharge": "Culture-and-Sensitivity-Nipple-discharge-300x300.jpg",
    "Culture and Sensitivity, CAPD Fluid": "Culture-and-Sensitivity-CAPD-Fluid-300x300.jpg",
    "Automated TB/AFB Culture Final Report": "Automated-TB-AFB-Culture-Final-Report-300x300.jpg",
    "DCP- Decarboxy Prothrombin PIVKA II": "DCP-Decarboxy-Prothrombin-PIVKA-II-300x300.jpg",
    "KOH Examination, BAL Fluid Test": "urine-sample-300x300.jpg",
    "Grams Stain, Eye Swab": "Grams-Stain-Eye-Swab-300x300.jpg"
  },
  {
    "Beta 2 Microglobulin, Urine": "kidney-3-300x300.jpg",
    "Chlorides, Serum": "Blood-Cells-300x300.jpg",
    "Cholinesterase (Pseudo), Serum": "liver-300x300.jpg",
    "Fat Globules, Urine Test": "kidney-3-300x300.jpg",
    "Legionella Antigen Detection, Urine Test": "kidney-3-300x300.jpg",
    "Herpes Simplex Virus I IgG Test": "antibody-300x300.jpg",
    "AFB Stain, Fluid": "AFB-Stain-Fluid-300x300.jpg",
    "Procalcitonin, Serum Test": "Pre-eclampsia-screening-Serum-300x300.jpg",
    "Coxsackie Serology (IgG, IgM)": "Digestive-Tract-300x300.jpg",
    "Adrenaline (Epinephrine), Urine 24H": "Adrenal-Glands-300x300.jpg",
    "Fungal Culture, Body Fluid Test": "Fungus-300x300.jpg",
    "Osmotic Fragility Test": "Blood-Test-300x300.jpg",
    "Nickel, Blood Test": "NextGen-Non-Invasive-Prenatal-Screening-Test-300x300.jpg",
    "Creatinine, Urine 24H": "kidney-3-300x300.jpg",
    "Culture and Sensitivity, PCD Drain": "Culture-and-Sensitivity-PCD-Drain-300x300.jpg",
    "CMV DNA Detection by Real Time PCR Urine": "44-1-300x300.jpg",
    "Proteins, Fluid Test": "Blood-Test-300x300.jpg",
    "Giemsa Stain, Blood Parasites Test": "Blood-Test-300x300.jpg",
    "Culture and Sensitivity, Tissue": "antibody-300x300.jpg",
    "CD20 IHC Single Marker, Tissue": "Blood-Cells-300x300.jpg",
    "Follicular Stimulating Hormone (FSH) Test": "urine-sample-300x300.jpg",
    "IHC-SINGLE MARKER (PR)": "IHC-SINGLE-MARKER-KI67-300x300.jpg",
    "Insulin Post, Serum Test": "Blood-Test-300x300.jpg",
    "Couple Carrier Screening": "DNA-300x300.jpg",
    "Albumin, Urine 24H": "kidney-3-300x300.jpg",
    "Beta-2-Glycoprotein I IgM Antibody Serum": "Blood-Cells-300x300.jpg",
    "Circulating Immune Complex (CIC)-IgM Antibodies": "Blood-Cells-300x300.jpg",
    "Hepatitis B Envelope Antibody (HBEAB) Test": "antibody-300x300.jpg",
    "Fever Profile, Basic Fever Profile": "fever-300x300.jpg",
    "Lead, Urine 24H Test": "kidney-3-300x300.jpg",
    "Calcium, Urine Spot": "urine-sample-300x300.jpg",
    "Hydatid Cyst (Echinococcus) IGG, Serum Test": "antibody-300x300.jpg",
    "KOH Examination, Nail Test": "Fungus-300x300.jpg",
    "Prolactin Test": "kidney-3-300x300.jpg",
    "Paul Bunnell Test (Infectious Mononucleosis) Test": "26-300x300.jpg",
    "Ganglioside IgM Antibody, Serum Test": "brain-spinalcord-300x300.jpg",
    "Cholesterol, LDL-Direct": "cholesterol-300x300.jpg",
    "HCV RNA Quantification (Viral Load) Test": "DNA-300x300.jpg",
    "Cortisol (4 PM)": "Blood-Cells-300x300.jpg",
    "Phospholipid Antibody (IgM) Test": "Blood-Test-300x300.jpg",
    "Grams Stain, CSF Test": "brain-spinalcord-300x300.jpg",
    "RDW Blood Test ": "antibody-300x300.jpg",
    "Grams Stain, ET Secretion Test": "virus-1-300x300.jpg",
    "Bun Creatinine Ratio": "kidney-3-300x300.jpg",
    "P-ANCA Test": "Organic-Acid-Screen-Quantitative-Urine-300x300.jpg",
    "Alcohol (Ethanol), Quantitative, Serum": "liver-300x300.jpg",
    "Parainfluenza 1, 2 & 3, IgM Antibody, Serum Test": "Bone-1-300x300.jpg",
    "Gliadin IGG Antibody Test": "antibody-300x300.jpg",
    "Tissue Transglutaminase IgG Antibody Test ": "Parathyroid-gland-300x300.jpg",
    "Hepatitis B Envelope Antigen (HBEAG) Test": "antibody-300x300.jpg",
    "Cytology, Pus": "group-A-streptococcus-bacteria-300x300.jpg",
    "BCR-ABL IS (International Scale) Transcript fusion Quantification by Real Time PCR -Minor": "BCR-ABL-IS-International-Scale-Transcript-fusion-Quantification-by-Real-Time-PCR-Minor-300x300.jpg",
    "CK-MB": "Blood-Cells-300x300.jpg",
    "Ketone Bodies, Urine Test": "Bone-1-300x300.jpg",
    "Cell Block": "Cell-Block-300x300.jpg",
    "AUTOMATED TB / AFB CULTURE URINE": "Automated-TB-AFB-Culture-300x300.jpg",
    "Aluminium, Serum": "Blood-Cells-300x300.jpg",
    "Measles (Rubeola) Serology": "antibody-300x300.jpg",
    "Culture and Sensitivity, Throat Swab": "Throat-Swab-300x300.jpg",
    "Cholesterol, Total": "cholesterol-300x300.jpg",
    "Galactomannan Antigen Test Serum Test": "Sterility-Test-300x300.jpg",
    "HLA B5 (B 51/52) BEHCETS DISEASE": "53-300x300.jpg",
    "Cytology, Serous Fluid": "Cytology-Serous-Fluid-300x300.jpg",
    "Fungal Culture, Bal fluid": "Fungal-Culture-Bal-fluid-300x300.jpg",
    "Grams Stain, Urethral Swab Test": "Urethra-300x300.jpg",
    "Immunoglobulin IgM Test": "Immune-System-300x300.jpg",
    "Grams Stain, Pus Test": "Sterility-Test-300x300.jpg",
    "Quadruple Marker Profile Test": "blood-clotting-2-300x300.jpg",
    "Arylsulphatase A, Blood": "Blood-Cells-300x300.jpg",
    "Haptoglobin Test": "Blood-Test-300x300.jpg",
    "Skin Biopsy DIF": "Sterility-Test-300x300.jpg",
    "Phosphorous, Serum Test": "blood-clotting-2-300x300.jpg",
    "Phospholipid Antibody (IgA) Test": "kidney-3-300x300.jpg",
    "Tacrolimus, Blood Test ": "glucose-300x300.jpg",
    "Mercury, Serum Test": "Blood-Cells-300x300.jpg",
    "Coombs Test Indirect (ICT)": "Blood-Cells-300x300.jpg",
    "Hepatitis A Virus (HAV) IGM Antibody Test": "antibody-300x300.jpg",
    "Special Stain For AFB": "kidney-3-300x300.jpg",
    "Brucella IgM Antibody": "Blood-Cells-300x300.jpg",
    "Centromere Antibody": "Blood-Cells-300x300.jpg",
    "Sodium, Urine 24H test ": "antibody-300x300.jpg",
    "Lung Cancer Panel Test": "Logistics-and-Handling-Charges-300x300.jpg",
    "Epstein Bar Virus IgM Antibody (VCA)": "16-300x300.jpg",
    "Erythropoietin, Serum Test": "kidney-3-300x300.jpg",
    "EBV NA IgM Antibody by EIA SERUM": "16-300x300.jpg",
    "ADA, Ascitic Fluid": "lungs-300x300.jpg",
    "Beta 2 Transferrin Carbohydrate": "Brain-300x300.jpg",
    "Thyroid Profile (T3, T4, TSH) Test ": "61-300x300.jpg",
    "Protein Electrophoresis, Urine Test": "Blood-Test-300x300.jpg",
    "Autoimmune Encephalitis Panel (CSF)": "brain-inflammation-300x300.jpg",
    "Fungal Culture, Stool": "Fungal-Culture-Stool-300x300.jpg",
    "Proteins, Urine Spot Test": "Blood-Test-300x300.jpg",
    "Hepatitis B Immunity Profile Get Tested with Hepatitis B Immunity Profile": "hepatitis-b-300x300.jpg",
    "Cytology, CSF": "Brain-Nervous-System-300x300.jpg",
    "Fungal Susceptibility and MIC Panel 5 Drugs Test": "Fungus-300x300.jpg",
    "CYTOLOGY REPORT": "CYTOLOGY-REPORT-300x300.jpg",
    "EBV NA IgG Antibody by CLIA Serum": "6-300x300.jpg",
    "Dengue IgG IgM and NS1 Antigen,Rapid": "15-300x300.jpg",
    "Immunocap Pediatric Allergy": "34-300x300.jpg",
    "Chromogranin A, Plasma": "Blood-Cells-300x300.jpg",
    "Estradiol (E2) Test": "ovary-300x300.jpg",
    "KOH Examination, Fluid Test": "KOH-Examination-ET-Secretion-300x300.jpg",
    "Operation Theatre Sterility Test (2 Swabs)": "brain-spinalcord-300x300.jpg",
    "Smooth Muscle Antibody (ASMA) Test ": "Smear-for-AFB-Stain-Sputum-DAY-1-300x300.jpg",
    "Anti SSDNA Antibody": "10-300x300.jpg",
    "GTT 1/2 Hour Plasma Glucose": "GTT-1-2-Hour-Plasma-Glucose-300x300.jpg",
    "Factor XII (Hageman) Activity, Plasma Test": "Sterility-Test-300x300.jpg",
    "Culture and Sensitivity, Wound Swab": "wound-300x300.jpg",
    "Platelet Antibody, Serum Test": "Adrenal-Glands-300x300.jpg",
    "Culture and Sensitivity, Vaginal Swab": "Female-Reproductive-System-300x300.jpg",
    "Cytology, Gastric Aspirate Fluid": "Cytology-Gastric-Aspirate-Fluid-300x300.jpg",
    "Lipase, Fluid Test": "pancreas-1-300x300.jpg",
    "Kappa & Lambda Light Chains- Free, Serum Test": "antibody-300x300.jpg"
  },
  {
    "Noradrenaline (Norepinephrine), Urine Test": "Blood-Test-300x300.jpg",
    "Ova Cyst, Stool Test": "Blood-Cells-300x300.jpg",
    "Hypertension Profile Hypertension Profile Testing": "hypertension-300x300.jpg",
    "Culture and Sensitivity, Tip": "Culture-and-Sensitivity-Tip-300x300.jpg",
    "Gamma GT (GGTP) Test": "liver-300x300.jpg",
    "Galactomannan Antigen Test Bal Fluid": "18-300x300.jpg",
    "Mycoplasma Pneumoniae IgM Antibody": "21-300x300.jpg",
    "Kappa Light Chains- Free, Serum Test": "kidney-3-300x300.jpg",
    "Immuno Fixation Electrophoresis (Quantitative), Urine Test": "Blood-Test-300x300.jpg",
    "Specific Gravity, Urine test ": "Blood-Cells-300x300.jpg",
    "Endomysial IgG Antibody, Serum": "555-300x300.jpg",
    "Cytomegalovirus (CMV) IgM Antibody": "antibody-300x300.jpg",
    "Thallium, Serum test ": "Blood-Test-300x300.jpg",
    "Sirolimus, Blood Test ": "brain-spinalcord-300x300.jpg",
    "Grams Stain, Tracheal secretion": "Grams-Stain-Tracheal-secretion-300x300.jpg",
    "Bullous Pemphigoid 180": "Bullous-Pemphigoid-180-300x300.jpg",
    "Potassium, Urine 24H Test": "kidney-3-300x300.jpg",
    "Second Opinion, Slide test ": "25-300x300.jpg",
    "Rubella Antibodies ( IgG & IgM )": "Arthritis-300x300.jpg",
    "MCV Test": "Blood-Cells-300x300.jpg",
    "Chromium, Blood": "Blood-Cells-300x300.jpg",
    "Activated Protein C (APC) Resistance, Plasma": "liver-300x300.jpg",
    "Cardiolipin Profile": "Blood-Cells-300x300.jpg",
    "Thyroglobulin Antibody (TG) Test ": "urine-sample-300x300.jpg",
    "Histopathology (Medium) Test": "cancer-cells_clipdrop-enhance-300x300.jpg",
    "Insulin Fasting Serum Test": "Blood-Test-300x300.jpg",
    "Oncomap Test": "Digestive-Tract-300x300.jpg",
    "Albumin, Serum": "Blood-Cells-300x300.jpg",
    "HBV-DNA Quantification (Viral load) Test": "liver-300x300.jpg",
    "Hepatitis B Core Antigen (HBCAg), IGM Antibody Test": "antibody-300x300.jpg",
    "Fructosamine, Serum Test": "Blood-Cells-300x300.jpg",
    "Immunohistochemistry (6 Markers) Test": "antibody-300x300.jpg",
    "GTT Fasting Plasma Glucose": "GTT-Fasting-Plasma-Glucose-300x300.jpg",
    "Lactate Test": "Blood-Cells-300x300.jpg",
    "Rheumatoid Arthritis Profile  ": "Bone-1-300x300.jpg",
    "Dengue Serology Test": "virus-1-300x300.jpg",
    "Serotonin (5HT), Urine 24H test ": "kidney-3-300x300.jpg",
    "Potassium Urine Spot Test": "PNH-Flow-Cytometry-flaer-300x300.jpg",
    "Smear for AFB Stain Sputum (DAY 1)": "Blood-Cells-300x300.jpg",
    "HSV DNA Detection I & II Serum Test": "DNA-300x300.jpg",
    "Stool Microscopic Examination": "Steroid-panel-A-5-steroids-300x300.jpg",
    "Microalbumin/Creatinine Ratio, Urine Spot Test": "urine-sample-300x300.jpg",
    "Galactose (Classical) Test": "Blood-Cells-300x300.jpg",
    "KOH Examination, Bronchial Wash Test": "KOH-Examination-Body-Fluid-300x300.jpg",
    "MapmyBiome": "kidney-3-300x300.jpg",
    "Diabetes Profile, Comprehensive Advanced Comprehensive Diabetes Profile": "diabetes-2-300x300.jpg",
    "Blood Culture and Sensitivity Automated, Adult": "Blood-Cells-300x300.jpg",
    "NIPT Basic Test": "NIPT-Non-invasive-Prenatal-Screening-Test-300x300.jpg",
    "Nickel, Urine Spot Test": "Sterility-Test-300x300.jpg",
    "Blood Culture And Sensitivity With Mic Value": "Blood-culture-and-sensitivity-with-Mic-value-300x300.jpg",
    "Cadmium, Urine 24h": "kidney-3-300x300.jpg",
    "KOH Examination, Throat Swab": "Stool-Sample-300x300.jpg",
    "Complement-Total (CH-50)": "Blood-Cells-300x300.jpg",
    "AFB Culture Automated Method": "lungs-300x300.jpg",
    "Apolipoprotein A1": "heart-2-300x300.jpg",
    "HIV P-24 Antigen Test": "antibody-300x300.jpg",
    "Brucella Serology": "Blood-Cells-300x300.jpg",
    "Grams Stain, Ear Swab": "Grams-Stain-Ear-Swab-300x300.jpg",
    "Chlamydia Trachomatis IgG Antibody": "Blood-Cells-300x300.jpg",
    "CMV-DNA Detection (Qualitative), Plasma": "DNA-300x300.jpg",
    "Alpha Fetoprotein (AFP)": "Blood-Cells-300x300.jpg",
    "Acid Phosphatase Total": "Acid-Phosphatase-Total-300x300.jpg",
    "DMD/BMD-79 exons Deletion/Duplication Analysis MLPA Blood": "70-300x300.jpg",
    "AUTOMATED TB / AFB CULTURE BAL": "AUTOMATED-TB-AFB-CULTURE-Body-fluids-300x300.jpg",
    "CA-72.4 , Serum": "Digestive-System-300x300.jpg",
    "Peripheral Smear for Malarial Parasites Test": "lymphatic-system-300x300.jpg",
    "H.pylori IGG Antibody, Serum Test": "Stomach-300x300.jpg",
    "Biochemical Analysis, Pericardial Fluid": "heart-2-300x300.jpg",
    "Biochemical Analysis, Pleural Fluid": "lungs-300x300.jpg",
    "Complement-4": "Blood-Cells-300x300.jpg",
    "Drug of Abuse, Panel-9 Drugs Test": "drug-300x300.jpg",
    "AFB Stain, Vaginal Swab": "AFB-Stain-Vaginal-Swab-300x300.jpg",
    "SARS-CoV-2 Detection by RT PCR Test ": "liver-300x300.jpg",
    "Cardiolipin IgM Antibody": "Blood-Cells-300x300.jpg",
    "Immunohistochemistry (1 Markers)": "Blood-Test-300x300.jpg",
    "Selenium, Serum test ": "antibody-300x300.jpg",
    "ADA, Serum": "lungs-300x300.jpg",
    "Glycosylated HB (HBA1C) Test": "Blood-Test-300x300.jpg",
    "Hemosiderin, Urine Test": "urine-sample-300x300.jpg",
    "KOH Examination, Sputum Test": "Fungus-300x300.jpg",
    "Erythrocyte Sedimentation Rate (ESR) Test": "Blood-Test-300x300.jpg",
    "IgG4, Serum Test": "liver-300x300.jpg",
    "Cardiac Enzymes": "Blood-Cells-300x300.jpg",
    "Smear for AFB Stain Sputum (DAY 2)": "Blood-Cells-300x300.jpg",
    "AFB Stain, Pus": "lungs-300x300.jpg",
    "Ganglioside Antibody,Serum": "brain-spinalcord-300x300.jpg",
    "Dengue IgG Antibody Test": "virus-1-300x300.jpg",
    "Cell Count & Cell Type, CSF": "brain-spinalcord-300x300.jpg",
    "Immunoglobulin IgG Test": "lungs-300x300.jpg",
    "Measles IgG Antibody, CSF": "antibody-300x300.jpg",
    "Lyme (Borrelia Burgdorferi) Antibody IgG Test": "urine-sample-300x300.jpg",
    "HIV Antibody Antigen 4th Generation": "antibody-300x300.jpg",
    "ADA, Synovial Fluid": "Joints-1-300x300.jpg",
    "Neuronal Antibody Profile Test": "Nervous-System-300x300.jpg",
    "Parathyroid Hormone (PTH) Test": "respiratory-system-300x300.jpg",
    "Dehydro Epiandrosterone Sulphate (DHEA-S) Test": "Adrenal-Glands-300x300.jpg",
    "BCR-ABL IS (International Scale) Transcript fusion Qualitative by Real Time PCR Bone Marrow": "kidney-3-300x300.jpg",
    "Oral Glucose Tolerance Test (O-GTT), Plasma": "Operation-Theatre-Sterility-Test-2-Swabs-1-300x300.jpg",
    "Parvovirus B19 IgG Antibody, Serum": "woman-with-skin-cancer-talking-with-doctor-1-scaled.jpg",
    "Cystic Fibrosis 5 Common Mutations (dF508 G542X G551D R553X 5T )": "DNA-300x300.jpg",
    "HCV RNA Detection (Qualitative) Test": "Blood-Cells-300x300.jpg",
    "Cysticercus (Taenia Solium) IgG Antibody Serum": "antibody-300x300.jpg",
    "Catecholamines, Urine": "Adrenal-Glands-300x300.jpg",
    "Cysticercus (Taenia Solium) IgG Antibody CSF": "antibody-300x300.jpg",
    "Herpes Simplex Virus I & II IgM Test": "antibody-300x300.jpg",
    "Calcium, Serum": "Blood-Cells-300x300.jpg",
    "Biochemical Analysis, Ascitic Fluid": "Peritoneal-300x300.jpg",
    "Glucose, (FBS,PLBS) Profile": "Glucose-FBSPLBS-300x300.jpg",
    "Food Intolerance Test": "Stomach-300x300.jpg",
    "NIPT (Non-invasive Prenatal Screening Test)": "DNA-300x300.jpg",
    "Streptococcus group B Antigen detection by Agglutination Serum": "Stool-Sample-300x300.jpg",
    "PNH Confirmation Test, Blood": "Blood-Test-300x300.jpg",
    "Liver Function Test (LFT) Test": "Blood-Cells-300x300.jpg"
  },
  {
    "Cytology, Urine": "kidney-3-300x300.jpg",
    "H.Pylori IGA Antibody Test": "Stomach-300x300.jpg",
    "Chikungunya RNA Detection By Real Time PCR": "12-300x300.jpg",
    "Chikungunya IgG Antibody": "30-300x300.jpg",
    "Chlamydia Pneumoniae IgA Antibody": "virus-1-300x300.jpg",
    "Grams Stain, Peritoneal Fluid Test": "Peritoneal-300x300.jpg",
    "Dengue Antigen (NS1), Rapid": "15-300x300.jpg",
    "Chlorides, Dialysis Fluid": "Blood-Cells-300x300.jpg",
    "Bile Acids-Total, Serum": "liver-300x300.jpg",
    "GTT 1st Hour Plasma Glucose": "GTT-1st-Hour-Plasma-Glucose-300x300.jpg",
    "Sodium, Serum Test ": "Smear-for-AFB-Stain-Sputum-DAY-3-300x300.jpg",
    "Drug of Abuse, Panel-5 Drugs 5 Panel Drug Test at Best Price (Drug of Abuse)": "drug-300x300.jpg",
    "SARS-CoV-2 Antibody (IgG)": "47-300x300.jpg",
    "Ganglioside IgG Antibody, Serum Test": "brain-spinalcord-300x300.jpg",
    "Bilirubin, Direct": "liver-300x300.jpg",
    "PLA2 Receptor Antibody": "Blood-Test-300x300.jpg",
    "Factor IX (Antihemophilic B) Activity Test": "Blood-Cells-300x300.jpg",
    "Myositis Profile-1 Myositis Profile-1 Blood Test Near Me": "Blood-Test-300x300.jpg",
    "Grams Stain, Vaginal Swab Test": "Female-Reproductive-System-300x300.jpg",
    "Drug of Abuse, Panel-9 Drugs Comprehensive Panel-9 Drug Test": "drug-300x300.jpg",
    "Rapid Malaria Test (PF) Test ": "Blood-Test-300x300.jpg",
    "Organic Acid Screen-Quantitative (Urine)": "Stool-Sample-300x300.jpg",
    "Kappa & Lambda Light Chains- Free, Urine Test": "Bone-1-300x300.jpg",
    "Hepatitis B surface Antigen (HBsAg) Elisa": "hepatitis-b-300x300.jpg",
    "Cytology, Bronchial Wash": "Cytology-Bronchial-Wash-300x300.jpg",
    "Stone Analysis Test ": "Spot-Urine-300x300.jpg",
    "Iron with TIBC Test": "Blood-Cells-300x300.jpg",
    "Blood Culture and Sensitivity": "Blood-Culture-and-Sensitivity-300x300.jpg",
    "Beta Galactosidase": "kidney-3-300x300.jpg",
    "Cytology, Guided Aspirate": "Cytology-Guided-Aspirate-300x300.jpg",
    "Semen Analysis test ": "Blood-Test-300x300.jpg",
    "Beta HCG, CSF": "Brain-300x300.jpg",
    "Thyroxine, Total (T4) Test ": "Parathyroid-gland-300x300.jpg",
    "PH, Fluid Test": "Blood-Cells-300x300.jpg",
    "Alkaline Phosphatase (ALP)": "Blood-Cells-300x300.jpg",
    "Immuno Fixation Electrophoresis (Quantitative), Serum Test": "kidney-3-300x300.jpg",
    "Mullerian Inhibiting Substance (AMH) Test": "kidney-3-300x300.jpg",
    "Prothrombin G20210A (Factor II) Mutation": "Proteins-fluid-300x300.jpg",
    "Cytology, Drain Fluid": "Peritoneal-300x300.jpg",
    "Arthritis Profile": "Arthritis-1-300x300.jpg",
    "Cholesterol, VLDL": "heart-2-300x300.jpg",
    "Phospholipid Antibody (IgG) Test": "Blood-Test-300x300.jpg",
    "Glucose, Fasting (FBS) Test": "Blood-Cells-300x300.jpg",
    "Torch Profile 10 Test ": "Parathyroid-gland-300x300.jpg",
    "Immunoglobulin Profile, Serum Test": "Brain-300x300.jpg",
    "Protein S Antigen, Plasma Test": "Blood-Test-300x300.jpg",
    "Biotinidase": "liver-300x300.jpg",
    "Anti DS DNA": "Blood-Cells-300x300.jpg",
    "Meningitis panel (CSF) multiplex PCR": "antibody-300x300.jpg",
    "IHC-SINGLE MARKER (ER)": "IHC-Breast-Panel-II-ERPRHER2NUKI67-300x300.jpg",
    "Sero Marker 1 (prostatic cancer screening)": "Blood-Test-300x300.jpg",
    "Grams Stain, CAPD Fluid": "Grams-Stain-CAPD-Fluid-300x300.jpg",
    "Lead, Blood Test": "Blood-Cells-300x300.jpg",
    "AUTOMATED TB / AFB CULTURE": "AUTOMATED-TB-AFB-CULTURE-BAL-300x300.jpg",
    "H.pylori Antigen Detection": "9-300x300.jpg",
    "Typhi. IgM Antibody Test ": "TSH-Ultrasensitive-ECLIA-Serum-300x300.jpg",
    "Giemsa Stain": "Blood-Test-300x300.jpg",
    "CA 125": "Female-Reproductive-System-300x300.jpg",
    "KOH Examination, Urine Test": "tissue-300x300.jpg",
    "Total Iron Binding Capacity (TIBC) Test ": "Sterility-Test-300x300.jpg",
    "Troponin-T Quantitative": "Parathyroid-gland-300x300.jpg",
    "Amphetamine, Urine": "kidney-3-300x300.jpg",
    "HSV I & II IgG Antibodies CSF Test": "antibody-300x300.jpg",
    "Cytology, Bartholin Cyst Fluid": "Cytology-Bartholin-Cyst-Fluid-300x300.jpg",
    "AFB Culture, Conventional Method": "lungs-300x300.jpg",
    "Chromium, Urine 24 H": "kidney-3-300x300.jpg",
    "Factor V Leiden Thrombophilia Test": "Blood-Cells-300x300.jpg",
    "Giardia Antigen, Stool Test": "small-intestine-300x300.jpg",
    "Fungal Stain, Tissue": "Fungal-Stain-Tissue-300x300.jpg",
    "Fructose, Semen Test": "Sperm-Test-300x300.jpg",
    "Anti Thrombin III Antigen": "Blood-Cells-300x300.jpg",
    "Sperm Antibody test ": "kidney-3-300x300.jpg",
    "Aspergillosis IGE": "Untitled-design-2-300x300.jpg",
    "Cytology, Pleural Fluid": "lungs-300x300.jpg",
    "SCL 70 IgG Antibody": "SARS_CoV_2-Abbott-ID-Now-300x300.jpg",
    "ADA, CSF": "brain-spinalcord-300x300.jpg",
    "Double Marker Profile Test": "DNA-300x300.jpg",
    "DPD 5FU Sensitivity Test": "Sterility-Test-300x300.jpg",
    "Surgical Profile Minor Test ": "Stool-Sample-300x300.jpg",
    "Interleukin 6": "Parathyroid-gland-300x300.jpg",
    "ALT (SGPT)": "liver-300x300.jpg",
    "Pneumocystis Carinii Detection Test": "Blood-Test-300x300.jpg",
    "Grams Stain, Throat Swab Test": "Throat-Swab-300x300.jpg",
    "KOH Examination, Corneal Scrappings": "KOH-Examination-CAPD-Fluid-300x300.jpg",
    "Filaria (Wuchereria Bancrofti) Antigen, Blood Test": "Blood-Cells-300x300.jpg",
    "Hemoglobin (HB%) Test": "Blood-Cells-300x300.jpg",
    "Fungal Culture, Guided Aspirate Test": "Fungus-300x300.jpg",
    "Gastrin, Serum Test": "Stomach-300x300.jpg",
    "MCHC Test": "Blood-Cells-300x300.jpg",
    "Plasminogen Activator Inhibitor-1 (PAI-1) / SERPINE-1, 4G/5G Genotyping": "11-300x300.jpg",
    "Glucose Challenge Test (GCT) Profile": "virus-1-300x300.jpg",
    "Fever Profile, Advanced Comprehensive Advanced Fever Profile Testing": "fever-300x300.jpg",
    "Acetone (Ketone), Urine": "liver-300x300.jpg",
    "Fungal Culture, Urine Test": "kidney-3-300x300.jpg",
    "KOH Examination, CAPD Fluid": "lungs-300x300.jpg",
    "Grams Stain, Guided Aspirate Test": "virus-1-300x300.jpg",
    "MTB Antibiogram (TB NGS) By Next Generation Sequencing-Pure Culture": "Red-White-Blood-Cells-and-Platelets-300x300.jpg",
    "Troponin-T Test ": "Parathyroid-gland-300x300.jpg",
    "GeneXpert Carba-R": "GeneXpert-Carba-R-300x300.jpg",
    "Culture and Sensitivity, Water": "antibody-300x300.jpg",
    "Culture and Sensitivity, Urine With MIC": "Culture-and-Sensitivity-Urine-With-MIC-300x300.jpg",
    "Immuno Fixation Electrophoresis (Qualitative), Urine Test": "Blood-Test-300x300.jpg",
    "Fungal Culture, Swab Test": "Nose-Swab-300x300.jpg",
    "Herpes Simplex Virus II IgM Test": "antibody-300x300.jpg",
    "HDL Cholesterol, Direct Test": "cholesterol-300x300.jpg",
    "Fungal Culture, ET Secretion": "Fungal-Culture-ET-Secretion-300x300.jpg",
    "PLA2 Receptor Antibody Quantitative, Serum": "kidney-3-300x300.jpg",
    "Insulin Antibody, Serum Test": "Insulin-Random-Serum-300x300.jpg",
    "Differential Count (DC) Test": "Immune-System-300x300.jpg",
    "Total IGE Test ": "Sterility-Test-300x300.jpg",
    "AFB Stain, Ascitic Fluid": "abdomen-300x300.jpg",
    "Smear for AFB Stain Sputum (DAY 3)": "Skin-Biopsy-DIF-300x300.jpg",
    "MPV (Mean Platelet Volume) Test": "antibody-300x300.jpg"
  },
  {
    "HCV Genotyping Test": "DNA-300x300.jpg",
    "Protein C Activity Test": "Prostate-300x300.jpg",
    "Leukamia Panel By FISH CLL": "antibody-300x300.jpg",
    "Heavy and Trace Metals profile-1": "Heavy-and-Trace-Metals-profile-1-300x300.jpg",
    "Toxoplasma DNA Detection By PCR-CSF": "Sterility-Test-300x300.jpg",
    "Pertussis IgG Antibody, Serum": "Blood-Cells-300x300.jpg",
    "Torch Profile 5 IgM Get Tested with Torch Profile 5 IgM ": "antibody-300x300.jpg",
    "Manganese, Urine 24H Test": "Bone-1-300x300.jpg",
    "HBV-DNA Detection (Qualitative) Test": "DNA-300x300.jpg",
    "Scrub Typhus IgM Antibody test ": "SARS-CoV-2-Three-Genes-RT-PCR_HMC-300x300.jpg",
    "Testosterone, Free Test ": "36-300x300.jpg",
    "Organic acid Semi Quantitative, Urine Test": "drug-300x300.jpg",
    "Influenza Screen and Type Test": "Brain-300x300.jpg",
    "Rabies Virus Antibodies Test ": "PSA-WITH-FREE-PSA-RATIO-300x300.jpg",
    "NBS 7 (NBS 6 + PKU)": "NBS-Hemoglobinopathies-300x300.jpg",
    "Rapid Malaria Test (PV) Test ": "Blood-Test-300x300.jpg",
    "Musk Antibody, Serum Test": "antibody-300x300.jpg",
    "Herpes Simplex Virus I & II IgG test": "antibody-300x300.jpg",
    "Intrinsic Factor Antibody IgG Test": "Interleukin-6-300x300.jpg",
    "Parietal Cell Antibody (PCA) Test": "lungs-300x300.jpg",
    "Toxoplasma IgG Antibody Test ": "pregnant-women-300x300.jpg",
    "Immuno Fixation Electrophoresis (Qualitative), Serum Test": "brain-spinalcord-300x300.jpg",
    "Parvovirus B19 IgM Antibody, Serum": "Stomach-300x300.jpg",
    "Torch Profile 5 IgG Test ": "Parathyroid-gland-300x300.jpg",
    "Meth Haemoglobin Test": "kidney-3-300x300.jpg",
    "Proteins Total, Serum Test": "Blood-Test-300x300.jpg",
    "Thyroid Stimulating Hormone (TSH) Test ": "antibody-300x300.jpg",
    "Insulin Random ,Serum": "Blood-Test-300x300.jpg",
    "TROP I QUANTITATIVE": "antibody-300x300.jpg",
    "Urea, Urine 24H Test ": "antibody-300x300.jpg",
    "Nasal Smear for Eosinophil Count Test": "myositis-300x300.jpg",
    "Phosphorous, 24Hrs Urine Test": "phospholipids-300x300.jpg",
    "KOH Examination, Hair Test": "Fungus-300x300.jpg",
    "HIV-1 Drug Resistance Test": "virus-300x300.jpg",
    "Thyroid Peroxidase Antibodies (TPO, Microsomal) Test ": "blood-clotting-2-300x300.jpg",
    "Hepatitis Profile Complete Hepatitis Profile": "hepatitis-300x300.jpg",
    "Torch Profile 10 Get Tested with Torch Profile 10 ": "liver-300x300.jpg",
    "HE4 (Epithelial Ovarian Cancer EOC Marker) Serum Test": "Female-Reproductive-System-300x300.jpg",
    "Stool Routine Examination": "kidney-3-300x300.jpg",
    "Leptospira IgG & IgM Antibody": "kidney-3-300x300.jpg",
    "Immunocap Rhinitis Mini": "Immunocap-Rhinitis-Maxi-300x300.jpg",
    "Protein S Activity Test": "Blood-Test-300x300.jpg",
    "Methylmalonic Acid (Quantitative) Urine Spot Test": "urine-sample-300x300.jpg",
    "Metabolic Screen, Urine": "DNA-300x300.jpg",
    "Microalbumin, Urine 24H Test": "DNA-300x300.jpg",
    "Histopathology (Small) Test": "tissue-300x300.jpg",
    "Triiodothyronine, Total (T3) Test ": "liver-300x300.jpg",
    "Paraneoplastic Syndrome/Neuronal Antibody Profile": "Blood-Cells-300x300.jpg",
    "TPMT Enzyme Activity Test ": "Blood-Cells-300x300.jpg",
    "Osmolality, Urine Test": "DNA-300x300.jpg",
    "SARS-CoV-2, Three Genes RT PCR_HMC": "antibody-300x300.jpg",
    "Lyme (Borrelia Burgdorferi) Antibody IgM test": "antibody-300x300.jpg",
    "Immunoglobulin IgA Test": "Immunocap-Rhinitis-Mini-300x300.jpg",
    "HTLV 1 And 2 Virus Total Antibody by CLIA Serum": "13-300x300.jpg",
    "Prealbumin, Serum Test": "Blood-Test-300x300.jpg",
    "Progesterone Test": "Blood-Test-300x300.jpg",
    "Urea Creatinine Ratio": "24-300x300.jpg",
    "PNH Flowcytometry flaer": "Fungus-300x300.jpg",
    "IHC-Breast Panel I (ER,PR,HER2NU)": "41-300x300.jpg",
    "Rett Syndrome Test ": "kidney-3-300x300.jpg",
    "Hb Electrophoresis Test": "Blood-Cells-300x300.jpg",
    "Hepatitis C Virus (HCV) Antibody Test": "antibody-300x300.jpg",
    "MPN Molecular Reflex Panel": "kidney-3-300x300.jpg",
    "Lactate Dehydrogenase (LDH), Fluid Test": "Lactate-CSF-300x300.jpg",
    "Mucopolysaccharides (MPS), Urine Test": "MTHFR-Mutations-300x300.jpg",
    "Serum Insulin Autoantibodies": "Sero-Marker-_1-prostatic-cancer-screening-300x300.jpg",
    "India Ink Preparation, CSF Test": "Immunohistochemistry-Single-Marker-Fish-Her2nu-300x300.jpg",
    "SS A (Ro) IgG Antibody test ": "Sperm-Test-300x300.jpg",
    "Torch Profile 8 Get Tested with Torch Profile 8 ": "pregnant-women-300x300.jpg",
    "POLG Gene Alpers Syndrome 1st Tire Test": "respiratory-300x300.jpg",
    "Immunocap Pollen Mini": "Immunocap-Pollen-1-300x300.jpg",
    "Treponema Pallidum Haemagglutination Assay (TPHA) Test ": "antibody-300x300.jpg",
    "Phenobarbitone Test": "lungs-300x300.jpg",
    "Selenium, Blood test ": "25-300x300.jpg",
    "Metanephrine-Free, Plasma Test": "Brain-300x300.jpg",
    "Histopathology Return of Blocks / Slides (Medium)": "Histopathology-Return-of-Blocks-_-Slides-Medium-300x300.jpg",
    "Thyroid Antibodies (TG, TPO) Test ": "Throat-Swab-300x300.jpg",
    "Thrombophilia Profile  Get Tested with Thrombophilia Profile ": "Blood-Test-300x300.jpg",
    "Noradrenaline (Norepinephrine), Plasma Test": "kidney-3-300x300.jpg",
    "Phenytoin (Eptoin) Test": "Sterility-Test-300x300.jpg",
    "Immunoglobulin Profile, CSF Test": "Immune-System-300x300.jpg",
    "Typhi. IgG Antibody": "heart-2-300x300.jpg",
    "Herpes (Varicella) Zoster IgG Antibody Test": "antibody-300x300.jpg",
    "TSH Receptor Antibodies (LATS-TSI), Serum Test ": "TROP-I-QUANTITATIVE-300x300.jpg",
    "Selenium, Urine test ": "Blood-Test-300x300.jpg",
    "Reticulocyte Count Test ": "Stool-Sample-300x300.jpg",
    "Histopathology (Extra Large) Test": "tissue-300x300.jpg",
    "Oxalate 24H Test": "OT-Swab-Test-300x300.jpg",
    "Phosphorous, Urine Spot Test": "kidney-3-300x300.jpg",
    "Rheumatoid Factor IgA Antibody": "Blood-Test-300x300.jpg",
    "Lipase Test": "Blood-Cells-300x300.jpg",
    "Rubella IgG Antibody ": "antibody-300x300.jpg",
    "Thyroxine Binding Globulin (TBG), Serum Test ": "Blood-Test-300x300.jpg",
    "Steroid panel A (5 steroids)": "Spinal-Cord-300x300.jpg",
    "Mumps IgG Antibody, CSF Test": "antibody-300x300.jpg",
    "Immunohistochemistry (7 Markers) Test": "antibody-300x300.jpg",
    "Histopathology Return of Blocks / Slides (Extra Large)": "Histopathology-Return-of-Blocks-_-Slides-Extra-Large-300x300.jpg",
    "Microalbumin, Urine Spot Test": "urine-sample-300x300.jpg",
    "HIT Antibody": "HIT-Antibody-300x300.jpg",
    "Histone Antibody": "Untitled-design-1-300x300.jpg",
    "Myoglobin, Serum Test": "kidney-3-300x300.jpg",
    "Proteins, Urine 24H Test": "kidney-3-300x300.jpg",
    "(IHC) Immunohistochemistry, Final Diagnostic Panel": "IHC-Immunohistochemistry-End-Diagnostic-Panel-300x300.jpg",
    "NMO-Neuromyelitis Optica Antibodies, CSF": "NMO-with-MOG-Antibody-Profile-for-Serum-300x300.jpg",
    "Oligoclonal Band by IEF, CSF Test": "obesity-300x300.jpg",
    "Pituitary Marker Profile Book the Pituitary Marker Profile": "Sterility-Test-300x300.jpg",
    "MTHFR Gene Polymorphisms Test": "MTB-Antibiogram-TB-NGS-by-Next-Generation-Sequencing-Pure-Culture-300x300.jpg",
    "Obesity Profile Comprehensive Obesity Profile Testing": "Adrenal-Glands-300x300.jpg",
    "Testosterone, Total Test ": "2-300x300.jpg",
    "Male Infertility Test": "antibody-300x300.jpg",
    "Throat Swab For KLB (Diphtheria) Test ": "antibody-300x300.jpg",
    "Immuno Fixation Electrophoresis (Qualitative), CSF Test": "Blood-Test-300x300.jpg",
    "Pre-Eclampsia Screening Serum": "kidney-3-300x300.jpg"
  },
  {
    "Thallium, Urine Spot Test ": "Blood-Test-300x300.jpg",
    "Measels (Rubeola) Serology": "Blood-Cells-300x300.jpg",
    "Urea, Serum Test ": "24-300x300.jpg",
    "Methionine, Quantitative Plasma Test": "urine-sample-300x300.jpg",
    "Peripheral Smear Study Test": "pcod-300x300.jpg",
    "NBS Hemoglobinopathies": "Blood-Test-300x300.jpg",
    "Inhibin A Test": "Blood-Test-300x300.jpg",
    "TB Quantiferon Test ": "Surgical-300x300.jpg",
    "Mycobacterium TB DNA Detection Test": "59-300x300.jpg",
    "Troponin-I Test  Test ": "Fatty-Acids-300x300.jpg",
    "Mumps IgM Antibody Test": "Brain-300x300.jpg",
    "HOMA Index Insulin Resistance Test": "HOMA-Index-Insulin-Resistance-Test-300x300.jpg",
    "Immunocap Pollen Maxi": "Immunocap-Pediatric-Allergy-300x300.jpg",
    "HLA B27 By PCR Test": "DNA-300x300.jpg",
    "Metabolic Disorder Panel Test": "urine-sample-300x300.jpg",
    "Immunocap Rhinitis Maxi": "Immunocap-Pollen-Mini-300x300.jpg",
    "Leptospira IgM Antibody Test": "Leptospira-IgM-antibodies-by-EIA-Serum-300x300.jpg",
    "Plasma Renin Direct, Plasma Test": "11-300x300.jpg",
    "Theophylline, Serum Test ": "Blood-Test-300x300.jpg",
    "IGLON5 ANTIBODY Serum": "Blood-Test-300x300.jpg",
    "Magnesium 24Hrs Urine Test": "antibody-300x300.jpg",
    "Immunohistochemistry (8 Markers)": "antibody-300x300.jpg",
    "Neisseria Gonorrhoea DNA Detection By Real Time PCR-Genital Swab": "NBS-7-NBS-6-PKU-300x300.jpg",
    "Saccharomyces Cervisiae (ASCA) IgG Antibody, Serum Test ": "5-300x300.jpg",
    "Methylmalonic Acid (Qualitative) Urine Spot Test": "Sterility-Test-300x300.jpg",
    "Syphilis Antibodies Treponema by EIA-Serum": "17-300x300.jpg",
    "Hepatitis B Core Antibody Total (HBcAb Total) Test": "antibody-300x300.jpg",
    "Potassium, Dialysis Fluid Test": "DNA-300x300.jpg",
    "Plasma Renin Activity (PRA), Plasma Test": "pitutary-gland.png",
    "Magnesium, Dialysis Fluid Test": "Blood-Cells-300x300.jpg",
    "Malarial Antigen, Vivax & Falciparum Test": "Malaria-QBC-300x300.jpg",
    "Nitroprusside Test, Urine Test": "kidney-3-300x300.jpg",
    "Porphobilinogen (PBG), Quantitative Urine 24 H Test": "Red-White-Blood-Cells-and-Platelets-300x300.jpg",
    "Normetanephrine-free, Plasma Test": "kidney-3-300x300.jpg",
    "Transferrin Test ": "antibody-300x300.jpg",
    "Red Blood Cells Count (RBC) Test ": "antibody-300x300.jpg",
    "Stool for H.Pylori Antigen": "Immune-System-300x300.jpg",
    "Triiodothyronine, Free (F-T3) Test ": "Sterility-Test-300x300.jpg",
    "Scrub Typhus Antibody": "lungs-300x300.jpg",
    "Packed Cell Volume (PCV) Test": "antibody-300x300.jpg",
    "Spot Urine Test": "kidney-3-300x300.jpg",
    "Streptococcus Group A Antigen Detection": "virus-1-300x300.jpg",
    "SERUM GALACTOMANNAN": "Sperm-Test-300x300.jpg",
    "Parvovirus B19 IgM Antibody by EIA Serum": "Parathyroid-gland-300x300.jpg",
    "PML RARA {t(9:22)} Quantitative, Blood Test": "Blood-Test-300x300.jpg",
    "PH, Urine Test": "Blood-Cells-300x300.jpg",
    "Nor Metanephrine, Urine 24H Test": "antibody-300x300.jpg",
    "AUTOMATED TB / AFB CULTURE TISSUE": "AUTOMATED-TB-AFB-CULTURE-URINE-300x300.jpg",
    "Albumin, Fluid": "Blood-Cells-300x300.jpg",
    "Grams Stain, Gastric Aspirate Fluid": "Grams-Stain-Gastric-Aspirate-Fluid-300x300.jpg",
    "Amylase, Fluid": "Digestive-System-300x300.jpg",
    "Biochemical analysis, PUS": "Biochemical-analysis-PUS-300x300.jpg",
    "Beta-Trace protein(BTP) CSF leakage in body fluid": "Beta-Trace-proteinBTP-CSF-leakage-in-body-fluid-300x300.jpg",
    "Cytology, Papsmear": "Sterility-Test-300x300.jpg",
    "EBV DNA Detection by PCR Test": "DNA-300x300.jpg",
    "Desmoglein III Antibody Test": "Desmoglein-III-Antibody-300x300.jpg",
    "Cyclosporin Test": "Cyclosporin-300x300.jpg",
    "FNAC Blind Procedure & Report": "FNAC-Blind-Procedure-Report-300x300.jpg",
    "Grams Stain, Tissue Test": "Sterility-Test-300x300.jpg",
    "Protein Electrophoresis, Serum Test": "Blood-Test-300x300.jpg",
    "AFB MDR Screen (MDRTB)": "lungs-300x300.jpg",
    "AFB Susceptibility, (1st line) 4 Drugs": "lungs-300x300.jpg",
    "Typhi. IgG & IgM Antibody": "Troponin-T-Quantitative-300x300.jpg",
    "Automated TB/AFB Culture Interim Report -1": "Automated-TB-AFB-Culture-Interim-Report-1-300x300.jpg",
    "Cystic Fibrosis, 5 mutations": "Cystic-Fibrosis-5-mutations-300x300.jpg",
    "Sickle Cell Test ": "brain-spinalcord-300x300.jpg",
    "Bilirubin, (Total, Direct, Indirect)": "liver-300x300.jpg",
    "Scrub Typhus IgG Antibody": "SARS-CoV-2-Three-Genes-RT-PCR_HMC-300x300.jpg",
    "SARS-CoV-2, Three Genes RT PCR": "antibody-300x300.jpg",
    "B Type Natriuretic Peptide (BNP) (NT-Pro)": "heart-2-300x300.jpg",
    "Tuberculin Skin Test (Mantoux) Test ": "heart-2-300x300.jpg",
    "Glucose, (RBS) Test": "Blood-Cells-300x300.jpg",
    "Glucose Tolerance Test (3 Samples) Test": "Blood-Test-300x300.jpg",
    "AFB Stain, Sputum (3 Samples)": "lungs-300x300.jpg",
    "BGP Bone Gla Protein (Osteocalcin), Serum": "Bone-1-300x300.jpg",
    "Chlamydia Trachomatis IgA Antibody": "Blood-Cells-300x300.jpg",
    "AFB Susceptibility, 10 Drugs": "lungs-300x300.jpg",
    "NMO-Neuromyelitis Optica Antibodies, Serum Test": "NMO-Neuromyelitis-Optica-Antibodies-CSF-300x300.jpg",
    "Potassium, Serum Test": "kidney-3-300x300.jpg",
    "Antinuclear Antibody, (ANA)": "Blood-Cells-300x300.jpg",
    "Prothrombin Time (PT) Test": "kidney-3-300x300.jpg",
    "Rh Antibody (Anti-D) Test ": "Respiratory-RP2-Plus-Panel-300x300.jpg",
    "Osmolality, Serum Test": "Ornithine-Quantitative-Urine-24H-300x300.jpg",
    "Anaemia Profile": "anaemia_clipdrop-enhance-300x300.jpg",
    "Fungal Culture, Fluid": "Fungal-Culture-Fluid-300x300.jpg",
    "AFB Stain, Tissue": "lungs-300x300.jpg",
    "Fungal Culture, Bronchial Wash Test": "Fungus-300x300.jpg",
    "Sodium, Dialysis Fluid test ": "Smear-for-AFB-Stain-Sputum-DAY-2-300x300.jpg",
    "Cytology for Fluid": "lungs-300x300.jpg",
    "Pregnancy Test, Urine Test": "kidney-3-300x300.jpg",
    "Stone screening profile": "heart-2-300x300.jpg",
    "ANA Profile": "ana-300x300.jpg",
    "Ceruloplasmin (Copper Oxidase), Serum Test": "liver-300x300.jpg",
    "Filaria (Wuchereria Bancrofti) Antibody, Serum Test": "antibody-300x300.jpg",
    "Skin Slits For AFB Smear Test ": "Serum-Insulin-Autoantibodies-300x300.jpg",
    "Reducing Substances, Stool Test ": "antibody-300x300.jpg",
    "Dengue Antigen (NS1), Serum ELISA Test": "virus-1-300x300.jpg",
    "Dopamine, Plasma Test": "Blood-Cells-300x300.jpg",
    "Smith IgG Antibody Test ": "Skin-300x300.jpg",
    "Anaerobic Culture & Identification": "Fatty-Acids-300x300.jpg",
    "Air Sampling for Sterility Check": "Sterility-Test-300x300.jpg",
    "Nicotine Metabolite (Quantitative), Serum": "kidney-3-300x300.jpg",
    "Galactomannan, Aspergillus Antigen test by EIA BAL Fluid": "18-300x300.jpg",
    "NextGen NIPS Advanced": "Nervous-System-300x300.jpg",
    "Gene Expert (Xpert MTB) Test": "lungs-300x300.jpg",
    "NMO with MOG Antibody Profile for Serum": "antibody-300x300.jpg",
    "Opiates Test": "cancer-cells_clipdrop-enhance-300x300.jpg",
    "Prostate Specific Antigen, Total (PSA) Test": "Blood-Cells-300x300.jpg",
    "TPMT Genotyping Test ": "Blood-Cells-300x300.jpg",
    "Glucose Challenge Test 2nd Hour": "Glucose-Challenge-Test-2nd-Hour-300x300.jpg",
    "NMDA Receptor Antibody Test": "kidney-3-300x300.jpg",
    "Respiratory RP2 Plus Panel": "Blood-Cells-300x300.jpg",
    "Complement-3": "Blood-Cells-300x300.jpg"
  },
  {
    "Cytology, Percicardial Fluid": "heart-2-300x300.jpg",
    "Dengue RNA PCR Test": "virus-1-300x300.jpg",
    "Urea, Urine Spot Test": "TLC-TOTAL-LEUCOCYTE-COUNT--300x300.jpg",
    "Grams Stain, Body Fluid": "Grams-Stain-Body-Fluid-300x300.jpg",
    "Biological Indicator Sterility Check": "Sterility-Test-300x300.jpg",
    "Desmoglein I Antibody Test": "Desmoglein-I-Antibody-300x300.jpg",
    "Triple Marker Profile Test  Test ": "antibody-300x300.jpg",
    "Drug of Abuse, Panel-5 Drugs Test": "drug-300x300.jpg",
    "Weil Felix Test ": "urine-sample-300x300.jpg",
    "Alpha Fetoprotein (AFP), CSF": "intestine-liver-300x300.jpg",
    "Sodium, Urine Spot test ": "antibody-300x300.jpg",
    "AFB Stain, Peritoneal Fluid": "abdomen-300x300.jpg",
    "Thrombotic Profile": "Blood-Cells-300x300.jpg",
    "Prostate Profile": "Blood-Test-300x300.jpg",
    "Nitrate, Urine Spot Test": "DNA-300x300.jpg",
    "Sperm DNA Fragmentation": "kidney-3-300x300.jpg",
    "D-Dimer Test": "Blood-Cells-300x300.jpg",
    "Prothrombin Time with INR Test": "kidney-3-300x300.jpg",
    "Glucose, Urine Fasting Test": "Glucose-Urine-Fasting-300x300.jpg",
    "ADA, Pericardial Fluid": "heart-2-300x300.jpg",
    "PSA WITH FREE PSA RATIO": "prothrombin-gene-mutation-300x300.jpg",
    "CD 4 Count Test": "thymus-gland-300x300.jpg",
    "Cytology, Synovial Fluid": "Joints-1-300x300.jpg",
    "Cytology, Sputum": "lungs-300x300.jpg",
    "Growth Hormone Test": "pituitary-gland-300x300.jpg",
    "Citrate, Urine 24 H": "kidney-3-300x300.jpg",
    "Glucose Challenge Test Fasting": "Glucose-Challenge-Test-Fasting-300x300.jpg",
    "Catecholamines Urine 24H Test": "Catecholamines-Urine-24H-300x300.jpg",
    "NIPT Advanced Plus Microdeletions and Duplications Test": "kidney-3-300x300.jpg",
    "Urine Drug Panel,10 Drugs": "kidney-3-300x300.jpg",
    "Cystic Fibrosis": "DNA-300x300.jpg",
    "Blood Grouping and Rh Typing": "Blood-Cells-300x300.jpg",
    "Nickel, Serum Test": "Blood-Test-300x300.jpg",
    "Widal Test, Tube Method Test ": "Microscope-Urine-1-300x300.jpg",
    "Total WBC Count (TC) Test ": "newborn-infections-300x300.jpg",
    "Blood Culture And Sensitivity profile": "Blood-Culture-and-Sensitivity-1-300x300.jpg",
    "Blood Culture and Sensitivity 1st Preliminary Report": "Blood-Culture-and-Sensitivity-1st-Preliminary-Report-300x300.jpg",
    "Grams Stain, Sputum Test": "respiratory-system-300x300.jpg",
    "Serotonin (5HT), Serum test ": "Blood-Test-300x300.jpg",
    "Pneumonia panel by FilmArray (Biofire)": "PML-Ra-Ra-300x300.jpg",
    "Blood Culture and Sensitivity Automated, Child": "Blood-Cells-300x300.jpg",
    "Cell Count & Cell Type, Pleural Fluid": "abdomen-300x300.jpg",
    "Grams Stain, Fluid": "Grams-Stain-Fluid-300x300.jpg",
    "CardioMap": "heart-2-300x300.jpg",
    "Chikungunya IgM Antibody": "virus-1-300x300.jpg",
    "Saccharomyces Cervisiae (ASCA) IgA test ": "antibody-300x300.jpg",
    "Urobilinogen, Urine Test ": "kidney-3-300x300.jpg",
    "Glucose Tolerance Test (5 Samples) Test": "Blood-Test-300x300.jpg",
    "Nicotine Metabolite (Quantitative), Urine Spot Test": "Blood-Test-300x300.jpg",
    "Protein C Antigen, Plasma Test": "Blood-Test-300x300.jpg",
    "Thyroxine, Free (F-T4) Test ": "Parathyroid-gland-300x300.jpg",
    "Ornithine Quantitative Urine 24H": "urine-sample-300x300.jpg",
    "Anti-SLA/LP,IgG Test": "Anti-SLA_LPIgG-300x300.jpg",
    "SAAG Test ": "antibody-300x300.jpg",
    "Glucose, Urine Post Lunch": "Glucose-Urine-Post-Lunch-300x300.jpg",
    "Cell Count & Cell Type, Bronchial Wash": "abdomen-300x300.jpg",
    "Fungal Culture, Nail Test": "Fungus-300x300.jpg",
    "OT Swab for Aerobic Culture Test": "kidney-3-300x300.jpg",
    "TSH (Ultrasensitive) ECLIA Serum": "Blood-Cells-300x300.jpg",
    "Sucrose Lysis Test": "Stool-Microscopic-Examination-300x300.jpg",
    "Treponema (Syphilis) Antibody Test ": "antibody-300x300.jpg",
    "Uric Acid, Urine Spot Test ": "kidney-3-300x300.jpg",
    "Ornithine Translocase Deficiency Test": "Ornithine-Quantitative-Plasma-300x300.jpg",
    "Torch Profile 5 IgM Test ": "Blood-Test-300x300.jpg",
    "Cystatin-C, Serum": "kidney-3-300x300.jpg",
    "Pyruvate, Blood (Pyruvic Acid) Test": "blood-clotting-2-300x300.jpg",
    "Rota Virus, Stool": "Arthritis-300x300.jpg",
    "Toxoplasma IgM Antibody Test ": "Sterility-Test-300x300.jpg",
    "Second Opinion, Block test ": "25-300x300.jpg",
    "Diabetes Profile, Basic Basic Diabetes Profile Testing": "diabetes-2-300x300.jpg",
    "Rheumatoid Factor (RA Factor) Test ": "DNA-300x300.jpg",
    "Triglycerides Test ": "DNA-300x300.jpg",
    "Digoxin Lanoxin Serum": "Digoxin-Lanoxin-Serum-300x300.jpg",
    "RNP IgG Antibody": "Arthritis-300x300.jpg",
    "Urine Routine Test": "kidney-3-300x300.jpg",
    "Tissue Transglutaminase Antibody IgA, Serum test ": "Parathyroid-gland-300x300.jpg",
    "Uric Acid, Serum Test ": "Urea-Creatinine-Ratio-300x300.jpg",
    "Cytology, Papsmear by LBC Method": "Sterility-Test-300x300.jpg",
    "Western Blot Test for HIV- 1 Test ": "Urine-Cotinine-300x300.jpg",
    "Culture and Sensitivity, Urine": "kidney-3-300x300.jpg",
    "Rheumatoid Factor IgG Antibody": "antibody-300x300.jpg",
    "Reducing Substances, Urine Test ": "Blood-Test-300x300.jpg",
    "Dopamine, Urine 24 H Test": "urine-sample-300x300.jpg",
    "Thyroglobulin, Serum Test ": "Blood-Test-300x300.jpg",
    "Cytology, Fine Needle Aspiration": "Mammary-Gland-300x300.png",
    "Cyclic Citrullinated Peptide (CCP) Antibody": "antibody-300x300.jpg",
    "Uric Acid, Urine 24H Test ": "kidney-3-300x300.jpg",
    "Spinal Muscular Atrophy [SMA] Mutation Analysis Test ": "Special-Stain-For-AFB-300x300.jpg",
    "Protein/Creatinine ratio, Urine Spot Test": "Blood-Test-300x300.jpg",
    "NextGen Non-Invasive Prenatal Screening Test": "NextGen-NIPS-Advanced-300x300.jpg",
    "Digoxin Test": "heart-2-300x300.jpg",
    "Widal Test, Slide Method Test ": "Urine-Drug-Panel10-Drugs-300x300.jpg",
    "Uric Acid Crystals, Fluid test ": "Blood-Cells-300x300.jpg",
    "SS B (La) IgG Antibody test ": "Sperm-DNA-Fragmentation-300x300.jpg",
    "Dengue IgM Antibody Test": "virus-1-300x300.jpg",
    "Culture and Sensitivity, Urethral Swab": "Urethra-300x300.jpg",
    "Thallium, Blood Test ": "Blood-Test-300x300.jpg",
    "UGT1A1(UDP-Glucuronosyl Transferase) Mutation, Blood Test ": "lungs-300x300.jpg",
    "TLC (TOTAL LEUCOCYTE COUNT )": "antibody-300x300.jpg",
    "Transferrin Saturation Test ": "43-300x300.jpg",
    "Cytomegalovirus (CMV) IgG Antibody": "antibody-300x300.jpg",
    "Cytology, Ascitic Fluid": "abdomen-300x300.jpg",
    "Metachromatic Leukodystrophy Test": "kidney-3-300x300.jpg",
    "Cytology, Peritoneal Fluid": "Peritoneal-300x300.jpg",
    "Dehydro Epiandrosterone (DHEA) Test": "Adrenal-Glands-300x300.jpg",
    "Zinc, Urine 24H Test ": "Blood-Cells-300x300.jpg",
    "Cytology, Nipple Discharge": "Mammary-Gland-300x300.png",
    "Duchene Muscular Dystrophy (DMD) Test": "DNA-300x300.jpg",
    "Zinc, Serum Test ": "liver-300x300.jpg",
    "Dihydrotestosterone (DHT) Test": "Blood-Cells-300x300.jpg",
    "Diptheria IGG Antibody Test": "lungs-300x300.jpg"
  }
];

module.exports = searchByOrgans;