const fs = require('fs');

const testnames = {

    "Absolute Eosinophil Count (AEC)": 150,
    "Absolute Lymphocyte Count": 180,
    "Absolute Monocyte Count": 180,
    "Absolute Neutrophil Count (ANC)": 180,
    "Absolute Reticulocyte Count": 200,
    "Acetaminophen (Paracetmol), Serum": 500,
    "Acetone (Ketone), Serum": 450,
    "Acetone (Ketone), Urine": 250,
    "Acetylcholine Receptor Antibody": 3500,
    "Acid Phosphatase Total": 400,
    "Activated Partial Thromboplastin Time (APTT)": 600,
    "Activated Protein C (APC) Resistance, Plasma": 4000,
    "Acute Leukemia Comprehensive Panel": 12000,
    "Acute Leukemia Diagnostic Panel": 10000,
    "ADA, Ascitic Fluid": 1000,
    "ADA, CSF": 1000,
    "ADA, Pericardial Fluid": 1000,
    "ADA, Peritoneal Fluid": 1000,
    "ADA, Pleural Fluid": 1000,
    "ADA, Serum": 1000,
    "ADA, Synovial Fluid": 1000,
    "ADAMTS 13 Autoantibody": 8000,
    "Adrenaline (Epinephrine), Plasma": 3500,
    "Adrenaline (Epinephrine), Urine 24H": 4000,
    "Adreno Corticotrophic Hormone (ACTH)": 3000,
    "AFB Culture Automated Method": 600,
    "AFB Culture, Conventional Method": 400,
    "AFB For Fluid": 400,
    "AFB MDR Screen (MDRTB)": 2500,
    "AFB Stain, Ascitic Fluid": 350,
    "AFB Stain, Body Fluid": 350,
    "AFB Stain, Bronchial Wash": 350,
    "AFB Stain, CSF": 350,
    "AFB Stain, ET Secretion": 350,
    "AFB Stain, Fluid": 350,
    "AFB Stain, Gastric Aspirate Fluid": 350,
    "AFB Stain, Guided Aspirate": 350,
    "AFB Stain, Pericardial Fluid": 350,
    "AFB Stain, Peritoneal Fluid": 350,
    "AFB Stain, Pleural Fluid": 350,
    "AFB Stain, Pus": 350,
    "AFB Stain, Sputum (3 Samples)": 400,
    "AFB Stain, Sputum": 400,
    "AFB Stain, Stool": 350,
    "AFB Stain, Synovial Fluid": 350,
    "AFB Stain, Tissue": 400,
    "AFB Stain, Tracheal secretion": 350,
    "AFB Stain, Urine": 350,
    "AFB Stain, Vaginal Swab": 350,
    "AFB Stain, Wound Swab": 350,
    "AFB Susceptibility, (1st line) 4 Drugs": 2000,
    "AFB Susceptibility, 10 Drugs": 4000,
    "Air Sampling for Sterility Check": 3000,
    "Albumin, Fluid": 300,
    "Albumin, Serum": 250,
    "Albumin, Urine 24H": 400,
    "Albumin, Urine Spot": 200,
    "Albumin/Globulin Ratio": 300,
    "Alcohol (Ethanol), Quantitative, Serum": 500,
    "Alcohol (Ethanol), Quantitative, Urine": 500,
    "Aldolase, Serum": 1000,
    "Aldosterone, Serum": 3000,
    "Aldosterone, Urine 24H": 3000,
    "Aldosterone/Renin Ratio": 4500,
    "Alkaline Phosphatase (ALP)": 300,
    "Alkaline Phosphatase with Bone Fraction (Ostase)": 600,
    "Allergy Child Panel": 5000,
    "Allergy Drug Panel MAXI": 9000,
    "Allergy Food Panel": 8000,
    "Allergy for Gluten": 2000,
    "Allergy Inhalant Panel": 6000,
    "Allergy Panel 12 Drugs": 8000,
    "Allergy Panel 7 Drugs": 5000,
    "Allergy panel-Nuts": 6000,
    "Allergy-Grass Panel": 5000,
    "Alpha 1 Antitrypsin, Serum": 3000,
    "Alpha Fetoprotein (AFP)": 800,
    "Alpha Fetoprotein (AFP), CSF": 1500,
    "ALT (SGPT)": 300,
    "Aluminium, Serum": 1000,
    "Amino Acid Screen-Qualitative, Plasma": 2500,
    "Amino Acid Screen, Urine Quantitative": 3000,
    "Amino Levulinic Acid (ALA) Quantitative, Urine 24H": 3500,
    "Ammonia": 700,
    "Amoebiasis IgG Antibody": 2000,
    "Amphetamine, Urine": 4000,
    "Amphiphysin (Neuronal Antigen) Antibody, Serum": 6000,
    "Amylase, Fluid": 400,
    "Amylase, Serum": 300,
    "ANA Profile": 2000,
    "Anaemia Profile": 1000,
    "Anaerobic Culture & Identification": 1500,
    "Androstenedione (A4), Serum": 2500,
    "Angiotensin Converting Enzyme (ACE)": 1000,
    "Angiotensin Converting Enzyme (ACE), CSF": 2500,
    "Anti DNase B, Serum": 800,
    "Anti DS DNA": 1000,
    "Anti MAG (Myelin associated Glycoprotein) Ab": 5000,
    "Anti Nuclear Antibody,(IFA Method)": 1200,
    "Anti SSDNA Antibody": 1200,
    "Anti Thrombin III Activity": 3000,
    "Anti Thrombin III Antigen": 3000,
    "Anti-SLA/LP,IgG Test": 4000,
    "Antidiuretic Hormone ADH": 3000,
    "Antineutrophil Cytoplasmic Antibody (ANCA)": 3500,
    "Antinuclear Antibody, (ANA)": 1200,
    "Antistreptolisin O (ASO)": 400,
    "AOA-Anti Ovarian Antibody, Serum": 4000,
    "Apolipoprotein A1 & B": 3000,
    "Apolipoprotein A1": 1500,
    "Apolipoprotein B": 1500,
    "Arsenic, Blood": 2000,
    "Arthritis Profile": 3000,
    "Arylsulphatase A, Blood": 6000,
    "Arylsulphatase B, Blood": 6000,
    "ASKA Skeletal (Striated) Muscle Antibody Serum": 4000,
    "Aspergillosis IGE": 2500,
    "Aspergillosis IGG": 2500,
    "Aspergillosis IGM": 2500,
    "AST (SGOT)": 300,
    "Autoimmune Encephalitis Panel (CSF)": 12000,
    "Autoimmune Liver Profile": 8000,
    "AUTOMATED TB / AFB CULTURE": 1000,
    "AUTOMATED TB / AFB CULTURE BAL": 1200,
    "AUTOMATED TB / AFB CULTURE Body fluids": 1200,
    "AUTOMATED TB / AFB CULTURE CSF": 1500,
    "AUTOMATED TB / AFB CULTURE PUS": 1200,
    "AUTOMATED TB / AFB CULTURE SPUTUM": 1000,
    "AUTOMATED TB / AFB CULTURE TISSUE": 1500,
    "AUTOMATED TB / AFB CULTURE URINE": 1200,
    "Automated TB/AFB Culture Final Report": 500,
    "Automated TB/AFB Culture Interim Report -1": 500,
    "Automated TB/AFB Culture Interim Report -2": 500,
    "B Type Natriuretic Peptide (BNP) (NT-Pro)": 2000,
    "Barbiturates, Urine Spot": 1500,
    "BCR-ABL IS (International Scale) Transcript fusion Quantification by Real Time PCR -Minor": 8000,
    "BeautyMap": 5000,
    "Bence Jones Proteins, Urine": 2000,
    "Benzodiazepine, Spot Urine": 1500,
    "Beta 2 Microglobulin, Serum": 1500,
    "Beta 2 Microglobulin, Urine": 1500,
    "Beta 2 Transferrin Carbohydrate": 2500,
    "Beta Galactosidase": 3000,
    "Beta HCG, CSF": 1500,
    "Beta HCG, Serum": 800,
    "Beta-2-Glycoprotein I IgA Antibody Serum": 2500,
    "Beta-2-Glycoprotein I IgG Antibody Serum": 2500,
    "Beta-2-Glycoprotein I IgM Antibody Serum": 2500,
    "Beta-D-Glucan Level by Protease Zymogen Colorimetry": 3500,
    "Beta-Trace protein(BTP) CSF leakage in body fluid": 3500,
    "BGP Bone Gla Protein (Osteocalcin), Serum": 2500,
    "Bicarbonate, Serum": 300,
    "Bile Acids-Total, Serum": 1000,
    "Bile Salts and Bile Pigments, Urine": 1200,
    "Bilirubin, (Total, Direct, Indirect)": 500,
    "Bilirubin, Direct": 300,
    "Bilirubin, Total": 500,
    "Biochemical Analysis, Ascitic Fluid": 1200,
    "Biochemical Analysis, CSF": 1200,
    "Biochemical Analysis, Pericardial Fluid": 1200,
    "Biochemical Analysis, Peritoneal Fluid": 1200,
    "Biochemical Analysis, Pleural Fluid": 1200,
    "Biochemical analysis, PUS": 1200,
    "Biochemical Analysis, Synovial Fluid": 1200,
    "Biological Indicator Sterility Check": 3000,
    "BIOPSY GUN": 1000,
    "Biotinidase": 2000,
    "Bleeding Time Clotting Time (BT & CT)": 500,
    "Blood Culture and Sensitivity": 2000,
    "Blood Culture and Sensitivity 1st Preliminary Report": 500,
    "Blood Culture and Sensitivity 2nd preliminary Report": 500,
    "Blood Culture and Sensitivity Final Report": 500,
    "Blood Culture and Sensitivity Anaerobic": 2500,
    "Blood Culture and Sensitivity Automated, Adult": 3000,
    "Blood Culture and Sensitivity Automated, Child": 3000,
    "Blood Culture And Sensitivity profile": 3000,
    "Blood Culture And Sensitivity With Mic Value": 3500,
    "Blood Culture and Sensitivity, Anaerobic-Profile": 3500,
    "Blood Grouping and Rh Typing": 300,
    "Blood Urea Nitrogen (BUN)": 300,
    "Bone Marrow Aspiration": 5000,
    "BRCA 1 and 2 Profile": 15000,
    "BRCA-1 & BRCA- 2": 15000,
    "Breast Marker Profile": 7000,
    "Brucella IgG Antibody": 1200,
    "Brucella IgM Antibody": 1200,
    "Brucella Serology": 1500,
    "Bullous Pemphigoid 180": 2000,
    "Bullous Pemphigoid 230": 2000,
    "Bun Creatinine Ratio": 400,
    "Calprotectin, Stool CLIA": 300,
    "C- Peptide": 600,
    "C-ANCA": 900,
    "C-ANCA-Elisa": 950,
    "C-Reactive Proteins (CRP)": 500,
    "C1 Esterase Inhibitor, Serum": 1300,
    "CA 125": 700,
    "CA (Cyfra) 21-1, Serum": 800,
    "CA 15.3": 850,
    "CA 19.9": 950,
    "CA-72.4 , Serum": 1000,
    "Cadmium, Blood": 1100,
    "Cadmium, Urine 24h": 1200,
    "Calcitonin (Thyrocalcitonin), Serum": 1250,
    "Calcium / Creatinine Ratio, Urine Spot": 1300,
    "Calcium, Dialysis Fluid": 1400,
    "Calcium, Ionized": 1500,
    "Calcium, Serum": 1600,
    "Calcium, Urine 24H": 1700,
    "Calcium, Urine Spot": 1800,
    "Calprotectin, Stool Rapid": 1900,
    "Cancer Detection Profile, Male Comprehensive Male Cancer Detection": 2000,
    "Cannabis (Marijuana), Urine": 2100,
    "Carbamazepine (Tegretol)": 2200,
    "Carcinoembryonic Antigen (CEA)": 2300,
    "Cardiac Enzymes": 2400,
    "Cardiac Risk Profile Get Tested with the Cardiac Risk": 2500,
    "Cardiolipin IgA Antibody": 2600,
    "Cardiolipin IgG Antibody": 2700,
    "Cardiolipin IgM Antibody": 2800,
    "Cardiolipin Profile": 2900,
    "CardioMap": 3000,
    "Catecholamines Urine 24H Test": 3100,
    "Catecholamines, Plasma": 3200,
    "Catecholamines, Urine": 3300,
    "CD 3, CD 4 & CD 8 Count": 3400,
    "CD 4 & CD 8 Count": 3500,
    "CD 4 Count Test": 3600,
    "CD 8 Count": 3700,
    "CD19": 3800,
    "CD20 IHC Single Marker, Tissue": 3900,
    "CD20": 4000,
    "Cell Block": 4100,
    "Cell Count & Cell Type, Ascitic Fluid": 4200,
    "Cell Count & Cell Type, Bronchial Wash": 4300,
    "Cell Count & Cell Type, CSF": 4400,
    "Cell Count & Cell Type, Dialysis Fluid": 4500,
    "Cell Count & Cell Type, Pericardial Fluid": 4600,
    "Cell Count & cell Type, Peritoneal Fluid": 4700,
    "Cell Count & Cell Type, Pleural Fluid": 4800,
    "Cell Count & Cell Type, Synovial Fluid Test": 4900,
    "Centromere Antibody": 5000,
    "Ceruloplasmin (Copper Oxidase), Serum Test": 5100,
    "Chemical Indicator Sterility Check": 5200,
    "Chikungunya IgG Antibody": 5300,
    "Chikungunya IgM Antibody": 5400,
    "Chikungunya RNA Detection By Real Time PCR": 5500,
    "Chlamydia Pneumoniae IgA Antibody": 5600,
    "Chlamydia Pneumoniae IgG Antibody": 5700,
    "Chlamydia Pneumoniae IgM Antibody": 5800,
    "Chlamydia Trachomatis DNA, Urine": 5900,
    "Chlamydia Trachomatis IgA Antibody": 6000,
    "Chlamydia Trachomatis IgG Antibody": 6100,
    "Chlamydia Trachomatis IgM Antibody": 6200,
    "Chlorides, Dialysis Fluid": 6300,
    "Chlorides, Serum": 6400,
    "Chlorides, Urine 24 H": 6500,
    "Chlorides, Urine Spot": 6600,
    "Cholesterol, HDL-Direct": 6700,
    "Cholesterol, LDL-Direct": 6800,
    "Cholesterol, Total": 6900,
    "Cholesterol, VLDL": 7000,
    "Cholinesterase (Pseudo), Serum": 7100,
    "Cholinesterase Acetyl (RBC), Blood": 7200,
    "Cholinesterase Acetyl, Plasma": 7300,
    "Chromium, Blood": 7400,
    "Chromium, Urine 24 H": 7500,
    "Chromogranin A, Plasma": 7600,
    "Chromosomal Micro Array": 7700,
    "Chromosomal MicroArray High Resolution": 7800,
    "Chromosomal Microarray": 7900,
    "Chyle, Urine": 8000,
    "Circulating Immune Complex (CIC)-IgM Antibodies": 8100,
    "Citrate, Urine 24 H": 8200,
    "CK-MB": 8300,
    "Clopidogrel Sensitivity": 8400,
    "Clostridium Difficile Toxin A and B, Stool": 8500,
    "CMV DNA Detection by Real Time PCR Urine": 8600,
    "CMV-DNA Detection (Qualitative), Plasma": 8700,
    "CMV-DNA Viral Load (Quantitative), Plasma": 8800,
    "Coagulation Profile Comprehensive Coagulation Profile": 8900,
    "Cobalt, Blood": 9000,
    "Cobalt, Urine 24 H": 9100,
    "Cocaine, Urine": 9200,
    "Cold Agglutination": 9300,
    "Complement-3": 9400,
    "Complement-4": 9500,
    "Complement-Total (CH-50)": 9600,
    "Complete Blood Count (CBC)": 9700,
    "Complete Blood Picture (CBP)": 9800,
    "Complete Urine Examination (CUE)": 9900,
    "Comprehensive Cardiology Panel": 10000,
    "Comprehensive Gastroenterology Panel": 10100,
    "Comprehensive Nephrology Panel": 10200,
    "Comprehensive Neurology Panel": 10300,
    "Comprehensive Orthopedics Panel": 10400,
    "Comprehensive Pediatrics Panel": 10500,
    "Comprehensive Pulmonology Panel": 10600,
    "Congenital Alopecia T-Cell Immunodeficiency": 10700,
    "Congenital Myotonia": 10800,
    "Coombs Test Direct (DCT)": 10900,
    "Coombs Test Indirect (ICT)": 11000,
    "Copper, Serum": 11100,
    "Copper, Urine 24H": 11200,
    "Cortisol (4 PM)": 11300,
    "Cortisol (8 AM)": 11400,
    "Cortisol, Free Urine 24H": 11500,
    "Couple Carrier Screening": 11600,
    "COVID-19 (RT PCR) AT OFFSITE": 11700,
    "COVID-19 (RT PCR) AT LAB": 11800,
    "Coxiella Burnetii IgG (Q Fever), Serum": 11900,
    "Coxiella Burnetii IgM (Q Fever), Serum": 12000,
    "Coxsackie IgG Antibody": 12100,
    "Coxsackie IgM Antibody": 12200,
    "Coxsackie Serology (IgG, IgM)": 12300,
    "CPK MB": 12400,
    "Creatine Kinase (CPK)": 12500,
    "Creatinine Clearance Test, Urine 24H": 12600,
    "Creatinine-GFR by MDRD": 12700,
    "Creatinine, Serum": 12800,
    "Creatinine, Urine 24H": 12900,
    "Creatinine, Urine Spot": 13000,
    "Cryoglobulin, Qualitative": 13100,
    "Cryptococcus Antigen, CSF": 13200,
    "Cryptococcus Antigen, Serum": 13300,
    "Cryptosporidium, Stool": 13400,
    "CSF Analysis": 13500,
    "Culture & Sensitivity , Tracheal secretion": 13600,
    "Culture And Identification, Anaerobic Bacteria Blood Single Bottle": 13700,
    "Culture and Sensitivity , ET Secretion": 13800,
    "Culture and Sensitivity RO Water": 13900,
    "Culture and Sensitivity with MIC values": 14000,
    "Culture and Sensitivity, Ascitic Fluid": 14100,
    "Culture and Sensitivity, Bal Fluid": 14200,
    "Culture and Sensitivity, Bartholin Fluid": 14300,
    "Culture and Sensitivity, Body Fluid": 14400,
    "Culture and Sensitivity, Bronchial Wash": 14500,
    "Culture and Sensitivity, CAPD Fluid": 14600,
    "Culture and Sensitivity, Catheter Tip": 14700,
    "Culture and Sensitivity, Cervical Swab": 14800,
    "Culture and Sensitivity, CSF": 14900,
    "Culture and Sensitivity, Drain Fluid": 15000,
    "Culture and Sensitivity, Ear / Eye Swab": 15100,
    "Culture and Sensitivity, ET Tip Mixed Growth": 15200,
    "Culture and Sensitivity, ET Tip": 15300,
    "Culture and Sensitivity, Fluid": 15400,
    "Culture And Sensitivity, Guided Aspirate": 15500,
    "Culture and Sensitivity, Nail": 15600,
    "Culture and Sensitivity, Nasal Swab": 15700,
    "Culture and Sensitivity, Nipple discharge": 15800,
    "Culture and Sensitivity, PCD Drain": 15900,
    "Culture and Sensitivity, Pericardial Fluid": 16000,
    "Culture and Sensitivity, Peritoneal Fluid": 16100,
    "Culture and Sensitivity, Pleural Fluid": 16200,
    "Culture and Sensitivity, Pus Mixed Growth": 16300,
    "Culture and Sensitivity, Pus": 16400,
    "Culture and Sensitivity, Serous Fluid": 16500,
    "Culture and Sensitivity, Sputum": 16600,
    "Culture and Sensitivity, Stool": 16700,
    "Culture and Sensitivity, Swab": 16800,
    "Culture and Sensitivity, Synovial Fluid": 16900,
    "Culture and Sensitivity, Throat Swab": 17000,
    "Culture and Sensitivity, Tip": 17100,
    "Culture and Sensitivity, Tissue": 17200,
    "Culture and Sensitivity, Urethral Swab": 17300,
    "Culture and Sensitivity, Urine": 17400,
    "Culture and Sensitivity, Urine With MIC": 17500,
    "Culture and Sensitivity, Vaginal Swab": 17600,
    "Culture and Sensitivity, Water": 17700,
    "Culture and Sensitivity, Wound Swab": 17800,
    "Cyclic Citrullinated Peptide (CCP) Antibody": 17900,
    "Cyclosporin Test": 18000,
    "Cystatin-C, Serum": 18100,
    "Cystic Fibrosis 5 Common Mutations (dF508 G542X G551D R553X 5T )": 18200,
    "Cystic Fibrosis": 18300,
    "Cystic Fibrosis, 5 mutations": 18400,
    "Cysticercus (Taenia Solium) IgG Antibody CSF": 18500,
    "Cysticercus (Taenia Solium) IgG Antibody Serum": 18600,
    "Cytology for Fluid": 18700,
    "CYTOLOGY REPORT": 18800,
    "Cytology, Ascitic Fluid": 18900,
    "Cytology, Bartholin Cyst Fluid": 19000,
    "Cytology, Bronchial Wash": 19100,
    "Cytology, CSF": 19200,
    "Cytology, Drain Fluid": 19300,
    "Cytology, Fine Needle Aspiration": 19400,
    "Cytology, Gastric Aspirate Fluid": 19500,
    "Cytology, Guided Aspirate": 19600,
    "Cytology, Nipple Discharge": 19700,
    "Cytology, Papsmear by LBC Method": 19800,
    "Cytology, Papsmear": 19900,
    "Cytology, Percicardial Fluid": 20000,
    "Cytology, Peritoneal Fluid": 20100,
    "Cytology, Pleural Fluid": 20200,
    "Cytology, Pus": 20300,
    "Cytology, Serous Fluid": 20400,
    "Cytology, Sputum": 20500,
    "Cytology, Synovial Fluid": 20600,
    "Cytology, Urine": 20700,
    "Cytomegalovirus (CMV) IgG Antibody": 20800,
    "Cytomegalovirus (CMV) IgM Antibody": 20900,
    "D-Dimer Test": 300,
    "DCP- Decarboxy Prothrombin PIVKA II": 600,
    "Dehydro Epiandrosterone (DHEA) Test": 900,
    "Dehydro Epiandrosterone Sulphate (DHEA-S) Test": 950,
    "Dengue Antigen (NS1), Rapid": 1000,
    "Dengue Antigen (NS1), Serum ELISA Test": 1100,
    "Dengue IgG Antibody Test": 1200,
    "Dengue IgG IgM and NS1 Antigen,Rapid": 1300,
    "Dengue IgM Antibody Test": 1400,
    "Dengue RNA PCR Test": 1500,
    "Dengue Serology Test": 1600,
    "Desmoglein I Antibody Test": 1700,
    "Desmoglein III Antibody Test": 1800,
    "Diabetes Profile, Basic Basic Diabetes Profile Testing": 1900,
    "Diabetes Profile, Comprehensive Advanced Comprehensive Diabetes Profile": 2000,
    "Differential Count (DC) Test": 2100,
    "Digoxin Lanoxin Serum": 2200,
    "Digoxin Test": 2300,
    "Dihydrotestosterone (DHT) Test": 2400,
    "Diptheria IGG Antibody Test": 2500,
    "DMD/BMD-79 exons Deletion/Duplication Analysis MLPA Blood": 2600,
    "Dopamine, Plasma Test": 2700,
    "Dopamine, Urine 24 H Test": 2800,
    "Double Marker Profile Test": 2900,
    "DPD 5FU Sensitivity Test": 3000,
    "Drug of Abuse, Panel-5 Drugs 5 Panel Drug Test at Best Price (Drug of Abuse)": 3100,
    "Drug of Abuse, Panel-5 Drugs Test": 3200,
    "Drug of Abuse, Panel-9 Drugs Comprehensive Panel-9 Drug Test": 3300,
    "Drug of Abuse, Panel-9 Drugs Test": 3400,
    "Duchene Muscular Dystrophy (DMD) Test": 3500,
    "EBV DNA Detection by PCR Test": 400,
    "EBV NA IgG Antibody by CLIA Serum": 500,
    "Electrolytes, 24 H Urine Test": 600,
    "Electrolytes, Dialysis Fluid Test": 700,
    "Electrolytes, Serum Test": 800,
    "Electrolytes, Urine Spot Test": 900,
    "Endomysial IgA Antibody, Serum Test": 1000,
    "Endomysial IgG Antibody, Serum": 1100,
    "Entamoeba Histolytica (Amoebiasis) Antibody Test": 1200,
    "Entamoeba histolytica detection by Wet Mount Pus": 1300,
    "Epstein Bar Virus IgG Antibody (VCA)": 1400,
    "Epstein Bar Virus IgM Antibody (VCA)": 1500,
    "Erythrocyte Sedimentation Rate (ESR) Test": 1600,
    "Erythropoietin, Serum Test": 1700,
    "Estradiol (E2) Test": 1800,
    "Estriol Unconjugated (E3)": 1900,
    "Everolimus": 2000,
    "EBV NA IgM Antibody by EIA SERUM": 2100,
    "Factor IX (Antihemophilic B) Activity Test": 2200,
    "Factor V (Proaccelerin) Activity, Plasma Test": 2300,
    "Factor V Leiden Mutant Detection, Blood Test": 2400,
    "Factor V Leiden mutation": 2500,
    "Factor V Leiden Thrombophilia Test": 2600,
    "Factor VII (Proconvertin) Activity, Plasma Test": 2700,
    "Factor VIII Activity (Anti Haemophilia A) Test": 2800,
    "Factor VIII Antigen (VW-Von Willebrand) Test": 2900,
    "Factor X (Stuart Factor) Activity, Plasma Test": 3000,
    "Factor XI (Rosenthal) Activity, Plasma Test": 3100,
    "Factor XII (Hageman) Activity, Plasma Test": 3200,
    "Factor XIII Activity Functional, Plasma Test": 3300,
    "Factor-I (Fibrinogen) Activity Test": 3400,
    "Factor-II (Prothrombin) Mutation Detection, Blood Test": 3500,
    "Fat Globules, Urine Test": 3600,
    "Fat, Stool Test": 3700,
    "Fatty Acids With Very Long Chains C22 To C26 Plasma": 3800,
    "Fecal Elastase": 3900,
    "Female Infertility Test": 4000,
    "Ferritin, Serum Test": 4100,
    "Fertility Profile Book the Most Reliable Fertility Profile": 4200,
    "Fever Profile, Advanced Comprehensive Advanced Fever Profile Testing": 4300,
    "Fever Profile, Basic Fever Profile": 4400,
    "Fibrinogen Degradation Product (FDP) Test": 4500,
    "Filaria (Wuchereria Bancrofti) Antibody, Serum Test": 4600,
    "Filaria (Wuchereria Bancrofti) Antigen, Blood Test": 4700,
    "FNAC Blind Procedure & Report": 4800,
    "Folate, Serum (Vit B-9) Test": 4900,
    "Folic Acid, RBC Test": 5000,
    "Follicular Stimulating Hormone (FSH) Test": 5100,
    "Food Intolerance Test": 5200,
    "Fragile X (FMR1)CGG Repeat Analysis": 5300,
    "Free Androgen Index (FAI), Serum Test": 5400,
    "Free Beta HCG, Serum Test": 5500,
    "Fructosamine, Serum Test": 5600,
    "Fructose, Semen Test": 5700,
    "Fungal AST": 5800,
    "Fungal Culture, Bal fluid": 5900,
    "Fungal Culture, Body Fluid Test": 6000,
    "Fungal Culture, Bronchial Wash Test": 6100,
    "Fungal Culture, ET Secretion": 6200,
    "Fungal Culture, Fluid": 6300,
    "Fungal Culture, Guided Aspirate Test": 6400,
    "Fungal Culture, Hair Test": 6500,
    "Fungal Culture, Nail Test": 6600,
    "Fungal Culture, Nasal Secretion": 6700,
    "Fungal Culture, Pleural Fluid": 6800,
    "Fungal Culture, Pus Test": 6900,
    "Fungal Culture, Skin Test": 7000,
    "Fungal Culture, Sputum Test": 7100,
    "Fungal Culture, Stool": 7200,
    "Fungal Culture, Swab Test": 7300,
    "Fungal Culture, Tissue Test": 7400,
    "Fungal Culture, Tracheal secretion": 7500,
    "Fungal Culture, Urine Test": 7600,
    "Fungal Stain, Tissue": 7700,
    "Fungal Susceptibility and MIC Panel 5 Drugs Test": 7800,
    "G6PD, Blood Test": 2500,
    "GAD 65 (Glutamic Acid Decarboxylase ) Antibodies Test": 2600,
    "Galactomannan Antigen Test Bal Fluid": 2700,
    "Galactomannan Antigen Test Serum Test": 2800,
    "Galactomannan, Aspergillus Antigen test by EIA BAL Fluid": 2900,
    "Galactose (Classical) Test": 3000,
    "Gamma GT (GGTP) Test": 3100,
    "Ganglioside Antibody,Serum": 3200,
    "Ganglioside IgG Antibody, Serum Test": 3300,
    "Ganglioside IgM Antibody, Serum Test": 3400,
    "Gastrin, Serum Test": 3500,
    "Gastrointestinal panel by FilmArray (Biofire) Stool": 3600,
    "Gene Expert (Xpert MTB) Test": 3700,
    "GeneXpert Carba-R": 3800,
    "Giardia Antigen, Stool Test": 3900,
    "Giemsa Stain": 4000,
    "Giemsa Stain, Blood Parasites Test": 4100,
    "Gliadin IGA Antibody Test": 4200,
    "Gliadin IGG Antibody Test": 4300,
    "Globulin, Serum Test": 4400,
    "Glomerular Basement Membrane (GBM) Antibody Test": 4500,
    "Glucose Challenge Test (GCT) Profile": 4600,
    "Glucose Challenge Test (GCT) Test": 4700,
    "Glucose Challenge Test 1st Hour": 4800,
    "Glucose Challenge Test 2nd Hour": 4900,
    "Glucose Challenge Test Fasting": 5000,
    "Glucose Tolerance Test (3 Samples) Test": 5100,
    "Glucose Tolerance Test (5 Samples) Test": 5200,
    "Glucose, (FBS,PLBS) Profile": 5300,
    "Glucose, (RBS) Test": 5400,
    "Glucose, Fasting (FBS) Test": 5500,
    "Glucose, Post Lunch (PLBS) Test": 5600,
    "Glucose, Urine Fasting Test": 5700,
    "Glucose, Urine Post Lunch": 5800,
    "Glucose, Urine Test": 5900,
    "Glycophorin A, Blood Test": 6000,
    "Glycosylated HB (HBA1C) Test": 6100,
    "Grams Stain, Ascitic Fluid Test": 6200,
    "Grams Stain, Body Fluid": 6300,
    "Grams Stain, Bronchial Wash Test": 6400,
    "Grams Stain, CAPD Fluid": 6500,
    "Grams Stain, CSF Test": 6600,
    "Grams Stain, Ear Swab": 6700,
    "Grams Stain, ET Secretion Test": 6800,
    "Grams Stain, Eye Swab": 6900,
    "Grams Stain, Fluid": 7000,
    "Grams Stain, Gastric Aspirate Fluid": 7100,
    "Grams Stain, Guided Aspirate Test": 7200,
    "Grams Stain, Pericardial Fluid Test": 7300,
    "Grams Stain, Peritoneal Fluid Test": 7400,
    "Grams Stain, Pleural Fluid Test": 7500,
    "Grams Stain, Pus Test": 7600,
    "Grams Stain, Semen Test": 7700,
    "Grams Stain, Sputum Test": 7800,
    "Grams Stain, Stool Test": 7900,
    "Grams Stain, Synovial Fluid Test": 8000,
    "Grams Stain, Throat Swab Test": 8100,
    "Grams Stain, Tissue Test": 8200,
    "Grams Stain, Tracheal secretion": 8300,
    "Grams Stain, Urethral Swab Test": 8400,
    "Grams Stain, Urine Test": 8500,
    "Grams Stain, Vaginal Swab Test": 8600,
    "Grams Stain, Wound Swab Test": 8700,
    "Growth Hormone Test": 8800,
    "GTT 1 1/2 Hour Plasma Glucose": 8900,
    "GTT 1/2 Hour Plasma Glucose": 9000,
    "GTT 1st Hour Plasma Glucose": 9100,
    "GTT 2nd Hour Plasma Glucose": 9200,
    "GTT Fasting Plasma Glucose": 9300,
    "H.pylori Antigen Detection": 2000,
    "H.Pylori IGA Antibody Test": 2000,
    "H.pylori IGG Antibody, Serum Test": 2500,
    "H.Pylori IGM Antibody Test": 2000,
    "Haemogram Test": 600,
    "Hanging Drop, Stool Test": 600,
    "Hanta Virus IGM Antibodies, Serum Test": 2500,
    "Haptoglobin Test": 800,
    "Hb Electrophoresis Test": 1200,
    "HBV-DNA Detection (Qualitative) Test": 4000,
    "HBV-DNA Quantification (Viral load) Test": 5000,
    "HCV Genotyping Test": 4000,
    "HCV RNA Detection (Qualitative) Test": 4000,
    "HCV RNA Quantification (Viral Load) Test": 5000,
    "HCV-IgM Antibody": 2500,
    "HCV-total Antibody by CLIA Serum": 4000,
    "HDL Cholesterol, Direct Test": 500,
    "HE4 (Epithelial Ovarian Cancer EOC Marker) Serum Test": 5000,
    "Heavy and Trace Metals profile-1": 4000,
    "Heavy and Trace Metals profile-2": 5000,
    "Heinz Bodies, Blood Test": 800,
    "Helicobacter Pylori IgG antibodies by CLIA Serum": 2500,
    "Hemoglobin (HB%) Test": 600,
    "Hemoglobin, Urine Test": 800,
    "Hemophilia Profile Best Prices for Hemophilia Profile": 5000,
    "Hemosiderin, Urine Test": 800,
    "Hepatitis A Virus (HAV) IGM Antibody Test": 2500,
    "Hepatitis A Virus Antibody, (IGG) Total Test": 2500,
    "Hepatitis B Core Antibody Total (HBcAb Total) Test": 5000,
    "Hepatitis B Core Antigen (HBCAg), IGM Antibody Test": 5000,
    "Hepatitis B Envelope Antibody (HBEAB) Test": 4000,
    "Hepatitis B Envelope Antigen (HBeAg) Elisa": 4000,
    "Hepatitis B Envelope Antigen (HBEAG) Test": 4000,
    "Hepatitis B Immunity Profile Get Tested with Hepatitis B Immunity Profile": 5000,
    "Hepatitis B Surface Antibody, Total (Anti HBS) Test": 4000,
    "Hepatitis B surface Antigen (HBsAg) Elisa": 4000,
    "Hepatitis B Surface Antigen (HBSAG) Rapid test": 4000,
    "Hepatitis B Surface Antigen (HBSAG) Test": 4000,
    "Hepatitis C Virus (HCV) Antibody Elisa": 4000,
    "Hepatitis C Virus (HCV) Antibody Test": 4000,
    "Hepatitis C Virus Antibody (Anti HCV) Rapid Test": 4000,
    "Hepatitis Delta Virus (HDV) Total Antibody Test": 5000,
    "Hepatitis E Virus (HEV) IgG Antibody Test": 4000,
    "Hepatitis E Virus (HEV) IgM Antibody Test": 4000,
    "Hepatitis Profile Complete Hepatitis Profile": 5000,
    "Herpes (Varicella) Zoster IgG Antibody Test": 4000,
    "Herpes (Varicella) Zoster IgM Antibody Test": 4000,
    "Herpes Simplex Virus I IgG Test": 4000,
    "Herpes Simplex Virus I IgM Test": 4000,
    "Herpes Simplex Virus I & II IgG test": 5000,
    "Herpes Simplex Virus I & II IgM Test": 5000,
    "Herpes Simplex Virus II IgG Test": 4000,
    "Herpes Simplex Virus II IgM Test": 4000,
    "HFE Hemochromatosis Whole Gene Test": 5000,
    "High Sensitivity CRP (HS-CRP) Test": 4000,
    "Histochemistry (special stain To Demonstarte Leprosy Bacilli)": 4000,
    "Histone Antibody": 4000,
    "Histopathology (Extra Large) Test": 5000,
    "Histopathology (Large) Test": 4000,
    "Histopathology (Medium) Test": 3000,
    "Histopathology (Small) Test": 2000,
    "Histopathology Return of Blocks / Slides (Extra Large)": 5000,
    "Histopathology Return of Blocks / Slides (Large)": 4000,
    "Histopathology Return of Blocks / Slides (Medium)": 3000,
    "Histopathology Return of Blocks / Slides (Small)": 2000,
    "Histopathology Slide Charges": 1000,
    "HIT Antibody": 4000,
    "HIV Antibody Elisa": 4000,
    "HIV Antibody Antigen 4th Generation": 4000,
    "HIV Antibody Test": 4000,
    "HIV I & II Antibody Rapid Test": 4000,
    "HIV P-24 Antigen Test": 4000,
    "HIV-1 Drug Resistance Test": 5000,
    "HIV-1 RNA Detection, Qualitative Test": 5000,
    "HIV-1- DNA Detection (Qualitative) Test": 5000,
    "HIV-1-RNA Quantification (Viral Load) Test": 5000,
    "HIV-2-RNA Quantification (Viral Load) Test": 5000,
    "HLA B27 By PCR Test": 5000,
    "HLA B27 Test": 4000,
    "HLA B5 (B 51/52) BEHCETS DISEASE": 5000,
    "HLA Cross Match Test": 4000,
    "HLA B 5, Blood Test": 4000,
    "HLA B51, Blood Test": 4000,
    "HLA-B 1502 for carbamazepine toxicity": 5000,
    "HLA-B27 Test": 4000,
    "HOMA Index Insulin Resistance Test": 4000,
    "Homocysteine Test": 4000,
    "Homogentisic Acid Test": 4000,
    "HPV-DNA Detection (Qualitative) Test": 4000,
    "HSV DNA Detection I & II Serum Test": 5000,
    "HSV DNA Detection I & II(CSF) Test": 5000,
    "HSV I & II IgG Antibodies CSF Test": 5000,
    "HTLV 1 And 2 Virus Total Antibody by CLIA Serum": 5000,
    "Hunters (MPS II) Test": 5000,
    "Hydatid Cyst (Echinococcus) IGG, Serum Test": 4000,
    "Hypertension Profile Hypertension Profile Testing": 4000,
    "HEPATITIS C IGM": 4000,
    "(IHC) Immunohistochemistry, End Diagnostic Panel": 12000,
    "(IHC) Immunohistochemistry, Final Diagnostic Panel": 12000,
    "(IHC) Immunohistochemistry, Lymphoma Panel": 10000,
    "IBD Profile (Inflammatory Bowel Disease) IBD (Inflammatory Bowel Disease) Profile Near Me": 4000,
    "IDH1 Test": 5000,
    "IGF BP3, Serum Test": 1500,
    "IgG4, Serum Test": 2000,
    "IGLON5 ANTIBODY Serum": 4000,
    "IHC-Breast Panel I (ER,PR,HER2NU)": 10000,
    "IHC-Breast Panel II (ER,PR,HER2NU,KI67)": 12000,
    "IHC-SINGLE MARKER (ER)": 3000,
    "IHC-SINGLE MARKER (HER2NU)": 3000,
    "IHC-SINGLE MARKER (KI67)": 3000,
    "IHC-SINGLE MARKER (PR)": 3000,
    "IHC-Two markers (ER,PR)": 6000,
    "Immature Platelet Fraction Test": 1500,
    "Immuno Fixation Electrophoresis (Qualitative), CSF Test": 2500,
    "Immuno Fixation Electrophoresis (Qualitative), Serum Test": 2500,
    "Immuno Fixation Electrophoresis (Qualitative), Urine Test": 2500,
    "Immuno Fixation Electrophoresis (Quantitative), Serum Test": 3500,
    "Immuno Fixation Electrophoresis (Quantitative), Urine Test": 3500,
    "Immunocap Fruit Panel": 5000,
    "Immunocap Pediatric Allergy": 5000,
    "Immunocap Pollen Maxi": 5000,
    "Immunocap Pollen Mini": 4000,
    "Immunocap Rhinitis Maxi": 5000,
    "Immunocap Rhinitis Mini": 4000,
    "Immunoglobulin IgA Test": 1500,
    "Immunoglobulin IgG Test": 1500,
    "Immunoglobulin IgM Test": 1500,
    "Immunoglobulin Profile, CSF Test": 2500,
    "Immunoglobulin Profile, Serum Test": 2500,
    "Immunohistochemistry (1 Markers)": 3500,
    "Immunohistochemistry (2 Markers) Test": 4000,
    "Immunohistochemistry (3 Markers) Test": 4500,
    "Immunohistochemistry (4 Markers) Test": 5000,
    "Immunohistochemistry (5 Markers) Test": 5500,
    "Immunohistochemistry (6 Markers) Test": 6000,
    "Immunohistochemistry (7 Markers) Test": 6500,
    "Immunohistochemistry (8 Markers)": 7000,
    "Immunohistochemistry Single Marker (Fish-Her2nu)": 3500,
    "India Ink Preparation, CSF Test": 1500,
    "Influenza Screen and Type Test": 1000,
    "Inhibin A Test": 3000,
    "Inhibin B Test": 3000,
    "Insulin Fasting Serum Test": 1200,
    "Insulin Post, Serum Test": 1200,
    "Insulin Random ,Serum": 1200,
    "Insulin Antibody, Serum Test": 2000,
    "Insulin Like Growth Factor (IGF)-1(Somatomedin C) Test": 2000,
    "Intact Parathyroid Hormone (iPTH) Test": 2000,
    "Interleukin 6": 2500,
    "Intrinsic Factor Antibody IgG Test": 1500,
    "Iron Profile Iron Profile Testing Near Me": 2000,
    "Iron Test": 1200,
    "Iron with TIBC Test": 1500,
    "IRT": 1500,
    "JAK-2 Mutation, Blood Test": 5000,
    "JAK2 V617 Mutation, with Reflex to Jaks Ex- 12, CALR EX-9 Mutation and MPL W515, S505 Mutation,BoneM": 7000,
    "JEV(Japanese Encephalitis) RNA Detection, CSF Test": 6000,
    "Jo-1 Antibody Test": 2500,
    "Kappa & Lambda Light Chains- Free, Serum Test": 3000,
    "Kappa & Lambda Light Chains- Free, Urine Test": 3500,
    "Kappa Light Chains- Free, Serum Test": 2500,
    "Ketone Bodies, Urine Test": 1200,
    "KOH Examination, BAL Fluid Test": 1500,
    "KOH Examination, Body Fluid": 1500,
    "KOH Examination, Bronchial Wash Test": 1500,
    "KOH Examination, CAPD Fluid": 1500,
    "KOH Examination, Corneal Scrappings": 1500,
    "KOH Examination, CSF Fluid": 1500,
    "KOH Examination, ET Secretion": 1500,
    "KOH Examination, Fluid Test": 1500,
    "KOH Examination, Hair Test": 1500,
    "KOH Examination, Nail Test": 1500,
    "KOH Examination, Nasal Secretion": 1500,
    "KOH Examination, Pleural fluid": 1500,
    "KOH Examination, Pus Test": 1500,
    "KOH Examination, Skin Scrappings Test": 1500,
    "KOH Examination, Sputum Test": 1500,
    "KOH Examination, Stool": 1500,
    "KOH Examination, Throat Swab": 1500,
    "KOH Examination, TIP": 1500,
    "KOH Examination, Tissue Test": 1500,
    "KOH Examination, Urine Test": 1500,
    "KRAS-12/13 Mutation Analysis Test": 6000,
    "Lactate CSF Test": 1500,
    "Lactate Dehydrogenase (LDH), Fluid Test": 1800,
    "Lactate Dehydrogenase (LDH), Serum Test": 2000,
    "Lactate Test": 1200,
    "LC-1 (Liver Cytosolic Antigen type-1) Antibody Test": 2500,
    "LD (Leishmania Dodovani) Bodies, Blood Test": 3000,
    "Lead, Blood Test": 2000,
    "Lead, Urine 24H Test": 2200,
    "Legionella Antigen Detection, Urine Test": 2500,
    "Leigh Syndrome Test": 4000,
    "Leishmania Antibody-IgG (Kala Azar) Test": 2800,
    "Leptin Test": 2500,
    "Leptospira Detection, Blood Test": 3000,
    "Leptospira Detection, CSF Test": 3200,
    "Leptospira Detection, Urine Test": 3000,
    "Leptospira IgG & IgM Antibody": 2800,
    "Leptospira IgG Antibody Test": 2700,
    "Leptospira IgM antibodies by EIA Serum": 2900,
    "Leptospira IgM Antibody Test": 2800,
    "Leukamia Panel By FISH CLL": 5000,
    "Levetiracetam, Serum Test": 2000,
    "Lipase Test": 1800,
    "Lipase, Fluid Test": 2000,
    "Lipase, Urine Test": 1800,
    "Lipid Profile Test": 2200,
    "Lipoprotein-(a) Test": 2500,
    "Lithium Test": 1500,
    "Liver Function Test (LFT) Test": 2200,
    "LKM I Antibody Test": 2800,
    "Logistics and Handling Charges": 500,
    "Lung Cancer Panel Test": 6000,
    "Lupus Anticoagulants (LAC) Test": 2500,
    "Luteinizing Hormone (LH) Test": 2000,
    "Lyme (Borrelia Burgdorferi) Antibody IgG Test": 3000,
    "Lyme (Borrelia Burgdorferi) Antibody IgM test": 3000,
    "Magnesium 24Hrs Urine Test": 1800,
    "Magnesium Test": 1500,
    "Magnesium, Dialysis Fluid Test": 2000,
    "Malaria QBC": 2500,
    "Malarial Antigen, Vivax & Falciparum Test": 2200,
    "Male Infertility Test": 3500,
    "Manganese, Blood Test": 2000,
    "Manganese, Serum Test": 2000,
    "Manganese, Urine 24H Test": 2200,
    "MapmyBiome": 5000,
    "Maternal Cell Contamination Test": 3000,
    "MCH Test": 1500,
    "MCHC Test": 1500,
    "MCV Test": 1500,
    "Measels (Rubeola) Serology": 2500,
    "Measles (Rubeola) IgG Antibody": 2000,
    "Measles (Rubeola) IgM Antibody": 2000,
    "Measles (Rubeola) Serology": 2500,
    "Measles IgG Antibody, CSF": 3000,
    "Meningitis panel (CSF) multiplex PCR": 4000,
    "Mercury, Blood Test": 2500,
    "Mercury, Serum Test": 2500,
    "Mercury, Urine 24H Test": 2700,
    "Metabolic Disorder Panel Test": 3500,
    "Metabolic Screen, Urine": 2000,
    "Metachromatic Leukodystrophy Test": 5000,
    "Metanephrine-Free, Plasma Test": 3000,
    "Metanephrine, Urine 24H": 3200,
    "Meth Haemoglobin Test": 2500,
    "Methadone (Dolophine), Urine Test": 2000,
    "Methionine, Quantitative Plasma Test": 3000,
    "Methylmalonic Acid (Qualitative) Urine Spot Test": 2500,
    "Methylmalonic Acid (Quantitative) Urine Spot Test": 2800,
    "MethylMalonic Acid(Quantitative), Serum": 3000,
    "Methylmalonic Acidemia Test": 3500,
    "Microalbumin, Urine 24H Test": 2000,
    "Microalbumin, Urine Spot Test": 1800,
    "Microalbumin/Creatinine Ratio, Urine Spot Test": 2200,
    "Microfilaria Detection, Blood Test": 2500,
    "Microscope Urine": 1500,
    "Microsporidium Detection by modified ZN Stain Stool": 3000,
    "MISMATCH REPAIR (MMR) PROTEIN IMMUNOHISTOCHEMISTRY ONLY": 5000,
    "Mitochondrial Antibody (AMA) Test": 3000,
    "Monospot (Infectious Mononucleosis) Test": 2000,
    "Morphine (Opiates), Urine Test": 2000,
    "MPN Molecular Reflex Panel": 5000,
    "MPO/PR3 Antibodies, Serum Test": 2800,
    "MPV (Mean Platelet Volume) Test": 1800,
    "MTB Antibiogram (TB NGS) By Next Generation Sequencing-Pure Culture": 6000,
    "MTHFR Gene Polymorphisms Test": 3500,
    "MTHFR Mutations": 3500,
    "Mucopolysaccharides (MPS), Urine Test": 3000,
    "Mullerian Inhibiting Substance (AMH) Test": 2500,
    "Mumps IgG Antibody Test": 2200,
    "Mumps IgG Antibody, CSF Test": 3000,
    "Mumps IgM Antibody Test": 2200,
    "Musk Antibody, Serum Test": 2500,
    "Myasthenia Gravis Profile": 4000,
    "Mycobacterium TB DNA Detection Test": 5000,
    "Mycoplasma Pneumoniae IgG Antibody": 2500,
    "Mycoplasma Pneumoniae IgM Antibody": 2500,
    "Myoglobin Urine Spot Test": 2000,
    "Myoglobin, Serum Test": 2200,
    "Myositis Profile-1 Myositis Profile-1 Blood Test Near Me": 4000,
    "Myositis Profile-1 Test": 4000,
    "Myositis Profile-IgG(16 Antigen)": 3500,
    "Nasal Smear for Eosinophil Count Test": 1800,
    "Natural Killer Cells (NKC), Blood Test": 2500,
    "NBS Hemoglobinopathies": 3500,
    "NBS 7 (NBS 6 + PKU)": 4000,
    "Neisseria Gonorrhoea DNA Detection By Real Time PCR-Genital Swab": 3500,
    "Neuron Specific Enolase, Serum Test": 3000,
    "Neuronal Antibody Profile Test": 4000,
    "NextGen NIPS Advanced": 8000,
    "NextGen Non-Invasive Prenatal Screening Test": 7500,
    "Nickel, Blood Test": 2000,
    "Nickel, Serum Test": 2000,
    "Nickel, Urine Spot Test": 2200,
    "Nicotine Metabolite (Quantitative), Serum": 2500,
    "Nicotine Metabolite (Quantitative), Urine Spot Test": 2700,
    "NIPT Advanced Plus Microdeletions and Duplications Test": 9000,
    "NIPT (Non-invasive Prenatal Screening Test)": 7000,
    "NIPT Basic Test": 6000,
    "Nitrate, Urine Spot Test": 2000,
    "Nitroprusside Test, Urine Test": 2200,
    "NMDA Receptor Antibody Test": 3000,
    "NMO with MOG Antibody Profile for Serum": 4000,
    "NMO-Neuromyelitis Optica Antibodies, CSF": 3500,
    "NMO-Neuromyelitis Optica Antibodies, Serum Test": 3500,
    "Nor Metanephrine, Urine 24H Test": 3200,
    "Noradrenaline (Norepinephrine), Plasma Test": 3000,
    "Noradrenaline (Norepinephrine), Urine Test": 3200,
    "Normetanephrine-free, Plasma Test": 3500
,
    "Obesity Profile Comprehensive Obesity Profile Testing": 5500,
    "Occult Blood, Stool Test": 1500,
    "Oligoclonal Band by IEF, CSF Test": 3000,
    "Oncomap Test": 8000,
    "Operation Theatre Sterility Test (2 Swabs)": 2000,
    "Opiates Test": 1800,
    "Oral Glucose Tolerance Test (O-GTT), Plasma": 2200,
    "Organic acid Semi Quantitative, Urine Test": 2500,
    "Ornithine Quantitative Plasma": 3000,
    "Ornithine Quantitative Urine 24H": 3200,
    "Ornithine Translocase Deficiency Test": 3500,
    "Osmolality, Serum Test": 1800,
    "Osmolality, Urine Test": 2000,
    "Osmotic Fragility Test": 2200,
    "OT Swab for Aerobic Culture Test": 2500,
    "Ova Cyst, Stool Test": 1800,
    "Oxalate 24H Test": 2000,
    "Organic Acid Screen-Quantitative (Urine)": 3000
,
    "BCR-ABL IS (International Scale) Transcript fusion Qualitative by Real Time PCR Bone Marrow": 12000,
    "P-ANCA Test": 3500,
    "P-ANCA-Elisa": 3700,
    "P1NP (Total N-Terminal Propeptide Of Type I Procol) Test": 4000,
    "Packed Cell Volume (PCV) Test": 800,
    "PAPP A Test": 3000,
    "Parainfluenza 1, 2 & 3, IgG Antibody, Serum Test": 2200,
    "Parainfluenza 1, 2 & 3, IgM Antibody, Serum Test": 2400,
    "Paraneoplastic Syndrome/Neuronal Antibody Profile": 6000,
    "Parathyroid Hormone (PTH) Test": 3500,
    "Parietal Cell Antibody (PCA) Test": 3000,
    "Parvovirus B19 IgG Antibody, Serum": 1800,
    "Parvovirus B19 IgM Antibody by EIA Serum": 2000,
    "Parvovirus B19 IgM Antibody, Serum": 2000,
    "Paul Bunnell Test (Infectious Mononucleosis) Test": 1500,
    "PCOD Profile Assess PCOD with Comprehensive PCOD Profile": 5000,
    "Peripheral Smear for Abnormal Cells Test": 1200,
    "Peripheral Smear for Malarial Parasites Test": 1300,
    "Peripheral Smear Study Test": 1200,
    "Pertussis IgG Antibody, Serum": 2500,
    "PH, Fluid Test": 1000,
    "PH, Urine Test": 1000,
    "Phenobarbitone Test": 2200,
    "Phenytoin (Eptoin) Test": 2200,
    "Phospholipid Antibody (IgA) Test": 3000,
    "Phospholipid Antibody (IgG) Test": 3000,
    "Phospholipid Antibody (IgM) Test": 3000,
    "Phosphorous, 24Hrs Urine Test": 2500,
    "Phosphorous, Dialysis Fluid Test": 2200,
    "Phosphorous, Serum Test": 1800,
    "Phosphorous, Urine Spot Test": 2000,
    "Pituitary Marker Profile Book the Pituitary Marker Profile": 5500,
    "PLA2 Receptor Antibody": 3500,
    "PLA2 Receptor Antibody Quantitative, Serum": 3700,
    "Plasma Renin Activity (PRA), Plasma Test": 3000,
    "Plasma Renin Direct, Plasma Test": 3200,
    "Plasminogen Activator Inhibitor-1 (PAI-1) / SERPINE-1, 4G/5G Genotyping": 4000,
    "Platelet Antibody, Serum Test": 2500,
    "Platelet Count Test": 1000,
    "PML Ra Ra t(15:17) Qualitative By PCR": 5000,
    "PML RARA {t(9:22)} Quantitative, Blood Test": 6000,
    "Pneumocystis Carinii Detection Test": 3500,
    "Pneumonia panel by FilmArray (Biofire)": 8000,
    "PNH Confirmation Test, Blood": 3500,
    "PNH Flowcytometry flaer": 4000,
    "POLG Gene Alpers Syndrome 1st Tire Test": 6000,
    "Porphobilinogen (PBG), Quantitative Urine 24 H Test": 3000,
    "Potassium Urine Spot Test": 1500,
    "Potassium, Dialysis Fluid Test": 2200,
    "Potassium, Serum Test": 1200,
    "Potassium, Urine 24H Test": 2000,
    "Pre-Eclampsia Screening Serum": 3500,
    "Prealbumin, Serum Test": 2200,
    "Pregnancy Test, Urine Test": 800,
    "Procalcitonin, Serum Test": 3000,
    "Progesterone Test": 2000,
    "Prolactin Test": 2500,
    "Prostate Profile": 4000,
    "Prostate Specific Antigen, Free Test": 2200,
    "Prostate Specific Antigen, Total (PSA) Test": 2200,
    "Protein C Activity Test": 3000,
    "Protein C Antigen, Plasma Test": 3500,
    "Protein Electrophoresis, Serum Test": 2500,
    "Protein Electrophoresis, Urine Test": 2500,
    "Protein S Activity Test": 3000,
    "Protein S Antigen, Plasma Test": 3500,
    "Protein Total with Albumin Test": 1800,
    "Protein/Creatinine ratio, Urine Spot Test": 2000,
    "Proteins Total, Serum Test": 2000,
    "Proteins, Fluid Test": 2200,
    "Proteins, Urine 24H Test": 2200,
    "Proteins, Urine Spot Test": 2000,
    "Prothrombin G20210A (Factor II) Mutation": 3500,
    "Prothrombin Time (PT) Test": 1500,
    "Prothrombin Time with INR Test": 2000,
    "PSA WITH FREE PSA RATIO": 3500,
    "Pyruvate, Blood (Pyruvic Acid) Test": 3000
,
    "Quadruple Marker Profile Test": 8000
,
    "Rabies Virus Antibodies Test ": 600,
    "Rapid Malaria Test (PF) Test ": 800,
    "Rapid Malaria Test (PV) Test ": 800,
    "RDW Blood Test ": 500,
    "Red Blood Cells Count (RBC) Test ": 500,
    "Reducing Substances, Stool Test ": 550,
    "Reducing Substances, Urine Test ": 550,
    "Respiratory RP2 Plus Panel": 1200,
    "Reticulocyte Count Test ": 600,
    "Rett Syndrome Test ": 4500,
    "Rh Antibody (Anti-D) Test ": 500,
    "Rheumatoid Arthritis Profile  ": 2000,
    "Rheumatoid Factor (RA Factor) Test ": 800,
    "Rheumatoid Factor IgG Antibody": 800,
    "Rheumatoid Factor IgM, Antibody": 800,
    "RNP IgG Antibody": 1000,
    "Rota Virus, Stool": 700,
    "Rubella Antibodies ( IgG & IgM )": 1000,
    "Rubella IgG Antibody ": 600,
    "Rubella IgM Antibody ": 600,
    "Rheumatoid Factor IgA Antibody": 800
,
    "SAAG Test ": 1000,
    "Saccharomyces Cervisiae (ASCA) IgA test ": 1200,
    "Saccharomyces Cervisiae (ASCA) IgG Antibody, Serum Test ": 1200,
    "SARS_CoV_2 Abbott ID Now": 1500,
    "SARS-CoV-2 Detection by RT PCR Test ": 1800,
    "SARS-CoV-2, Three Genes RT PCR": 2000,
    "SARS-CoV-2, Three Genes RT PCR_HMC": 2200,
    "SCL 70 IgG Antibody": 800,
    "Scrub Typhus Antibody": 900,
    "Scrub Typhus IgG Antibody": 900,
    "Scrub Typhus IgM Antibody test ": 900,
    "Second Opinion, Block test ": 2500,
    "Second Opinion, Slide test ": 2000,
    "Selenium, Blood test ": 700,
    "Selenium, Serum test ": 700,
    "Selenium, Urine test ": 700,
    "Semen Analysis test ": 1200,
    "Sero Marker 1 (prostatic cancer screening)": 1800,
    "Serotonin (5HT), Serum test ": 900,
    "Serotonin (5HT), Urine 24H test ": 900,
    "SERUM GALACTOMANNAN": 1000,
    "Serum Insulin Autoantibodies": 1200,
    "Sickle Cell Test ": 700,
    "Sirolimus, Blood Test ": 1500,
    "Skin Biopsy DIF": 2000,
    "Skin Slits For AFB Smear Test ": 1000,
    "Smear for AFB Stain Sputum (DAY 1)": 1200,
    "Smear for AFB Stain Sputum (DAY 2)": 1200,
    "Smear for AFB Stain Sputum (DAY 3)": 1200,
    "Smith IgG Antibody Test ": 800,
    "Smooth Muscle Antibody (ASMA) Test ": 1000,
    "Sodium, Dialysis Fluid test ": 700,
    "Sodium, Serum Test ": 700,
    "Sodium, Urine 24H test ": 700,
    "Sodium, Urine Spot test ": 700,
    "Special Stain For AFB": 1000,
    "Specific Gravity, Urine test ": 550,
    "Sperm Antibody test ": 1200,
    "Sperm DNA Fragmentation": 1500,
    "Spinal Muscular Atrophy [SMA] Mutation Analysis Test ": 3000,
    "Spot Urine Test": 600,
    "SS A (Ro) IgG Antibody test ": 1000,
    "SS B (La) IgG Antibody test ": 1000,
    "Steroid panel A (5 steroids)": 1500,
    "Stone Analysis Test ": 1200,
    "Stone screening profile": 1200,
    "Stool for H.Pylori Antigen": 700,
    "Stool Microscopic Examination": 600,
    "Stool Routine Examination": 600,
    "Streptococcus Group A Antigen Detection": 800,
    "Streptococcus group B Antigen detection by Agglutination Serum": 800,
    "Sucrose Lysis Test": 1000,
    "Surgical Profile Minor Test ": 2000,
    "Syphilis Antibodies Treponema by EIA-Serum": 1000,
    "SARS-CoV-2 Antibody (IgG)": 1500
,
    "Tacrolimus, Blood Test ": 1500,
    "TB Quantiferon Test ": 2500,
    "Testosterone, Free Test ": 1200,
    "Testosterone, Total Test ": 1200,
    "Tetanus Toxoid-IgG Antibodies, Serum Test ": 1000,
    "Thallium, Blood Test ": 1500,
    "Thallium, Serum test ": 1500,
    "Thallium, Urine Spot Test ": 1500,
    "Theophylline, Serum Test ": 1200,
    "Throat Swab For KLB (Diphtheria) Test ": 1000,
    "Thrombophilia Profile  Get Tested with Thrombophilia Profile ": 2000,
    "Thrombotic Profile": 1800,
    "Thyroglobulin Antibody (TG) Test ": 1200,
    "Thyroglobulin, Serum Test ": 1200,
    "Thyroid Antibodies (TG, TPO) Test ": 1500,
    "Thyroid Peroxidase Antibodies (TPO, Microsomal) Test ": 1500,
    "Thyroid Profile (T3, T4, TSH) Test ": 1500,
    "Thyroid Stimulating Hormone (TSH) Test ": 1200,
    "Thyroxine Binding Globulin (TBG), Serum Test ": 1000,
    "Thyroxine, Free (F-T4) Test ": 1200,
    "Thyroxine, Total (T4) Test ": 1200,
    "Tissue Transglutaminase Antibody IgA, Serum test ": 1000,
    "Tissue Transglutaminase IgG Antibody Test ": 1000,
    "Torch Profile 10 Get Tested with Torch Profile 10 ": 2000,
    "Torch Profile 10 Test ": 2000,
    "Torch Profile 5 IgG Test ": 1800,
    "Torch Profile 5 IgM Get Tested with Torch Profile 5 IgM ": 1800,
    "Torch Profile 5 IgM Test ": 1800,
    "Torch Profile 8 Get Tested with Torch Profile 8 ": 1800,
    "Total IGE Test ": 1200,
    "Total Iron Binding Capacity (TIBC) Test ": 1000,
    "Total WBC Count (TC) Test ": 600,
    "Toxoplasma DNA Detection By PCR-CSF": 2000,
    "Toxoplasma IgG Antibody Test ": 1200,
    "Toxoplasma IgM Antibody Test ": 1200,
    "TPMT Enzyme Activity Test ": 1500,
    "TPMT Genotyping Test ": 1500,
    "Transferrin Saturation Test ": 1000,
    "Transferrin Test ": 1000,
    "Treponema (Syphilis) Antibody Test ": 1200,
    "Treponema Pallidum Haemagglutination Assay (TPHA) Test ": 1200,
    "Triglycerides Test ": 800,
    "Triiodothyronine, Free (F-T3) Test ": 1200,
    "Triiodothyronine, Total (T3) Test ": 1200,
    "Triple Marker Profile Test  Test ": 2000,
    "TROP I QUANTITATIVE": 1500,
    "Troponin-I Test  Test ": 1500,
    "Troponin-T Quantitative": 1500,
    "Troponin-T Test ": 1500,
    "TSH (Ultrasensitive) ECLIA Serum": 1500,
    "TSH Receptor Antibodies (LATS-TSI), Serum Test ": 1200,
    "Tuberculin Skin Test (Mantoux) Test ": 800,
    "Typhi. IgG & IgM Antibody": 1000,
    "Typhi. IgG Antibody": 1000,
    "Typhi. IgM Antibody Test ": 1000,
    "TLC (TOTAL LEUCOCYTE COUNT )": 600
,
    "UGT1A1(UDP-Glucuronosyl Transferase) Mutation, Blood Test ": 1500,
    "Urea Creatinine Ratio": 800,
    "Urea, Serum Test ": 1000,
    "Urea, Urine 24H Test ": 1200,
    "Urea, Urine Spot Test": 1000,
    "Uric Acid Crystals, Fluid test ": 1200,
    "Uric Acid, Serum Test ": 1000,
    "Uric Acid, Urine 24H Test ": 1200,
    "Uric Acid, Urine Spot Test ": 1000,
    "Urine Cotinine Test": 1500,
    "Urine Drug Panel,10 Drugs": 2000,
    "Urine Routine Test": 600,
    "Urobilinogen, Urine Test ": 800
,
    "Weil Felix Test ": 1500,
    "Western Blot Test for HIV- 1 Test ": 4000,
    "Widal Test, Slide Method Test ": 1200,
    "Widal Test, Tube Method Test ": 1500
,
    "Zinc, Serum Test ": 700,
    "Zinc, Urine 24H Test ": 800
}

const array3 = [];
Object.keys(testnames).forEach(funct)
function funct(item){
    let item1 = item;
    array3.push(`${item1}`);
}

const data = `const testRates = ${JSON.stringify(Object.keys(testnames))};\nmodule.exports = testnames;`;

// Write the string to a file
fs.writeFile('testnames12.js', data, (err) => {
    if (err) throw err;
    console.log('The file has been saved!');
});